fn main() {
    generate_tests_from_spec()
}

// If the "gen-tests" feature is absent,
// this function will be compiled down to nothing
#[cfg(any(not(feature = "gen-tests"), not(feature = "std")))]
fn generate_tests_from_spec() {}

// If the feature is present, generate tests
// from any .txt file present in the specs/ directory
//
// Test cases are present in the files in the
// following format:
//
// ```````````````````````````````` example [options]
// markdown
// .
// expected html output
// ````````````````````````````````
//
// [options] is passed to `bitflags::parser::from_str_strict` to set parser options.
#[cfg(all(feature = "gen-tests", feature = "std"))]
fn generate_tests_from_spec() {
    use std::fs::{self, File};
    use std::io::{Read, Write};
    use std::path::PathBuf;

    // This is a hardcoded path to the CommonMark spec because it is not situated in
    // the specs/ directory. It's in an array to easily chain it to the other iterator
    // and make it easy to eventually add other hardcoded paths in the future if needed
    let hardcoded = [
        ("./third_party/CommonMark/spec.txt", ""),
        (
            "./third_party/CommonMark/smart_punct.txt",
            "ENABLE_SMART_PUNCTUATION",
        ),
        ("./third_party/GitHub/gfm_table.txt", "ENABLE_TABLES"),
        (
            "./third_party/GitHub/gfm_strikethrough.txt",
            "ENABLE_STRIKETHROUGH",
        ),
        ("./third_party/GitHub/gfm_tasklist.txt", "ENABLE_TASKLISTS"),
    ];
    let hardcoded_iter = hardcoded
        .iter()
        .map(|(path, opts)| (PathBuf::from(path), Some(opts)));

    // Create an iterator over the files in the specs/ directory that have a .txt extension
    let mut spec_files = fs::read_dir("./specs")
        .expect("Could not find the 'specs' directory")
        .filter_map(Result::ok)
        .map(|d| (d.path(), None))
        .filter(|(p, _)| p.extension().map(|e| e.to_owned()).is_some())
        .chain(hardcoded_iter)
        .collect::<Vec<_>>();
    // Sort by spec names
    spec_files.sort_by(|(p, _), (q, _)| p.file_stem().cmp(&q.file_stem()));

    for (file_path, opts) in &spec_files {
        let mut raw_spec = String::new();

        File::open(&file_path)
            .and_then(|mut f| f.read_to_string(&mut raw_spec))
            .expect("Could not read the spec file");

        let rs_test_file = PathBuf::from("./tests/suite/")
            .join(file_path.file_name().expect("Invalid filename"))
            .with_extension("rs");

        let mut spec_rs =
            File::create(&rs_test_file).expect(&format!("Could not create {:?}", rs_test_file));

        let spec_name = file_path.file_stem().unwrap().to_str().unwrap();

        let spec = if let Some(opts) = opts {
            Spec::new_with_opts(&raw_spec, opts)
        } else {
            Spec::new_infer_opts(&raw_spec)
        };
        let mut n_tests = 0;

        spec_rs
            .write_all(b"// This file is auto-generated by the build script\n")
            .unwrap();
        spec_rs
            .write_all(b"// Please, do not modify it manually\n")
            .unwrap();
        spec_rs
            .write_all(b"\nuse super::test_markdown_html;\n")
            .unwrap();

        for (i, testcase) in spec.enumerate() {
            spec_rs
                .write_fmt(format_args!(
                    r###"
#[test]
fn {}_test_{i:04}_l{line}() {{
    let original = r##"{original}"##;
    let expected = r##"{expected}"##;

    test_markdown_html(original, expected, {options:?});
}}
"###,
                    spec_name,
                    i = i + 1,
                    original = testcase.original,
                    expected = testcase.expected,
                    options = testcase.options,
                    line = testcase.line,
                ))
                .unwrap();

            n_tests += 1;
        }

        println!(
            "cargo:warning=Generated {} tests in {:?}",
            n_tests, rs_test_file
        );
    }

    // write mods to suite/mod.rs
    let suite_mod_file = PathBuf::from("./tests/suite/mod").with_extension("rs");

    let mut mod_rs =
        File::create(&suite_mod_file).expect(&format!("Could not create {:?}", &suite_mod_file));

    mod_rs
        .write_all(b"// This file is auto-generated by the build script\n")
        .unwrap();
    mod_rs
        .write_all(b"// Please, do not modify it manually\n")
        .unwrap();
    mod_rs
        .write_all(b"\npub use super::test_markdown_html;\n\n")
        .unwrap();

    for (file_path, _) in &spec_files {
        let mod_name = file_path.file_stem().unwrap().to_str().unwrap();
        mod_rs.write_all(b"mod ").unwrap();
        mod_rs.write_all(mod_name.as_bytes()).unwrap();
        mod_rs.write_all(b";\n").unwrap();
    }
}

#[cfg(feature = "gen-tests")]
pub struct Spec<'a> {
    spec: &'a str,
    options: String,
    current_line: usize,
}

#[cfg(feature = "gen-tests")]
impl<'a> Spec<'a> {
    pub fn new_with_opts(spec: &'a str, opts: &str) -> Self {
        Spec {
            spec,
            options: opts.to_string(),
            current_line: 1,
        }
    }

    pub fn new_infer_opts(spec: &'a str) -> Self {
        let opts = spec
            .lines()
            .next()
            .and_then(|line| line.strip_prefix("Parser options:"))
            .unwrap_or("")
            .trim()
            .trim_matches('`');
        Spec::new_with_opts(spec, opts)
    }
}

#[cfg(feature = "gen-tests")]
pub struct TestCase {
    pub original: String,
    pub expected: String,
    pub options: String,
    pub line: usize,
}

#[cfg(feature = "gen-tests")]
impl<'a> Iterator for Spec<'a> {
    type Item = TestCase;

    fn next(&mut self) -> Option<TestCase> {
        let spec = self.spec;
        let prefix = "```````````````````````````````` example";

        let (i_start, options, line) = spec.find(prefix).and_then(|pos| {
            let (options, _) = spec[(pos + prefix.len())..].split_once('\n')?;
            let line = self.current_line + spec[..pos].lines().count();
            Some((pos + prefix.len() + options.len() + 1, options, line))
        })?;

        let i_end = spec[i_start..]
            .find("\n.\n")
            .map(|pos| (pos + 1) + i_start)?;

        let e_end = spec[i_end + 2..]
            .find("````````````````````````````````\n")
            .map(|pos| pos + i_end + 2)?;

        let options = join_options(&[&self.options, options]);

        self.current_line += spec[..e_end + 33].lines().count();
        self.spec = &self.spec[e_end + 33..];

        let test_case = TestCase {
            original: spec[i_start..i_end].to_string().replace("→", "\t"),
            expected: spec[i_end + 2..e_end].to_string().replace("→", "\t"),
            options,
            line,
        };

        Some(test_case)
    }
}

#[cfg(feature = "gen-tests")]
fn join_options(parts: &[&str]) -> String {
    let parts = parts
        .iter()
        .map(|p| p.trim())
        .filter(|p| !p.is_empty())
        .collect::<Vec<_>>();
    parts.join(" | ")
}
