// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn gfm_tasklist_test_1() {
    let original = r##"- [ ] foo
- [x] bar
"##;
    let expected = r##"<ul>
<li style="list-style-type: '\2610   ';">foo</li>
<li style="list-style-type: '\2612   ';">bar</li>
</ul>
"##;

    test_markdown_html(original, expected, false, false, false);
}

#[test]
fn gfm_tasklist_test_2() {
    let original = r##"- [x] foo
  - [ ] bar
  - [x] baz
- [ ] bim
"##;
    let expected = r##"<ul>
<li style="list-style-type: '\2612   ';">foo
<ul>
<li style="list-style-type: '\2610   ';">bar</li>
<li style="list-style-type: '\2612   ';">baz</li>
</ul>
</li>
<li style="list-style-type: '\2610   ';">bim</li>
</ul>
"##;

    test_markdown_html(original, expected, false, false, false);
}
