// This file is auto-generated by the build script
// Please, do not modify it manually

pub use super::test_markdown_html;

mod regression;
mod footnotes;
mod table;
mod spec;
mod gfm_table;
mod gfm_strikethrough;
mod gfm_tasklist;
