// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn blockquotes_tags_test_0001_l17() {
    let original = r##"> This is a normal blockquote without tag.
"##;
    let expected = r##"<blockquote><p>This is a normal blockquote without tag.</p></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0002_l23() {
    let original = r##"> [!NOTE]
> Note blockquote
"##;
    let expected = r##"<blockquote class="markdown-alert-note"><p>Note blockquote</p></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0003_l30() {
    let original = r##"> [!TIP]
> Tip blockquote
"##;
    let expected = r##"<blockquote class="markdown-alert-tip"><p>Tip blockquote</p></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0004_l37() {
    let original = r##"> [!IMPORTANT]
> Important blockquote
"##;
    let expected = r##"<blockquote class="markdown-alert-important"><p>Important blockquote</p></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0005_l44() {
    let original = r##"> [!WARNING]
> Warning blockquote
"##;
    let expected = r##"<blockquote class="markdown-alert-warning"><p>Warning blockquote</p></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0006_l51() {
    let original = r##"> [!CAUTION]
> Caution blockquote
"##;
    let expected = r##"<blockquote class="markdown-alert-caution"><p>Caution blockquote</p></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0007_l59() {
    let original = r##"> [!CAUTION]
"##;
    let expected = r##"<blockquote class="markdown-alert-caution"></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0008_l66() {
    let original = r##"> [!CAUTION]
> Line 1.
> Line 2.
"##;
    let expected = r##"<blockquote class="markdown-alert-caution"><p>Line 1.
Line 2.</p></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0009_l76() {
    let original = r##"> [!CAUTION]
> Line 1.
> [!CAUTION]
> Line 2.
"##;
    let expected = r##"<blockquote class="markdown-alert-caution"><p>Line 1.
[!CAUTION]
Line 2.</p></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0010_l88() {
    let original = r##"> [!CAUTION]
> Line 1.
> > [!TIP]
> Line 2.
"##;
    let expected = r##"<blockquote class="markdown-alert-caution"><p>Line 1.</p><blockquote class="markdown-alert-tip"><p>Line 2.</p></blockquote></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0011_l98() {
    let original = r##"> [!CAUTION]
> Line 1.


> [!TIP]
> Line 2.
"##;
    let expected = r##"<blockquote class="markdown-alert-caution"><p>Line 1.</p></blockquote><blockquote class="markdown-alert-tip"><p>Line 2.</p></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0012_l110() {
    let original = r##"> > [!CAUTION]
> > Line 1.
> Line 2.
"##;
    let expected = r##"<blockquote><blockquote class="markdown-alert-caution"><p>Line 1.
Line 2.</p></blockquote></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0013_l120() {
    let original = r##"> [!CAUTION]	
> Line 1.
> > [!NOTE]      
> > Line 2.
"##;
    let expected = r##"<blockquote class="markdown-alert-caution"><p>Line 1.</p>
<blockquote class="markdown-alert-note"><p>Line 2.</p></blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0014_l132() {
    let original = r##"> [!caution]	
> Line 1.
> > [!note]      
> > Line 2.
"##;
    let expected = r##"<blockquote class="markdown-alert-caution"><p>Line 1.</p>
<blockquote class="markdown-alert-note"><p>Line 2.</p></blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0015_l144() {
    let original = r##"  * loose lists

    > [!NOTE]
    > sink ships
"##;
    let expected = r##"<ul><li><p>loose lists</p>
<blockquote class="markdown-alert-note"><p>sink ships</p></blockquote>
</li></ul>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0016_l156() {
    let original = r##"> [!NOTE]
sink ships

> [!NOTE]
> sink ships

  * loose lists

    > [!NOTE]
    sink ships

    > [!NOTE]
    > sink ships
"##;
    let expected = r##"<blockquote class="markdown-alert-note"><p>sink ships</p></blockquote>
<blockquote class="markdown-alert-note"><p>sink ships</p></blockquote>
<ul><li><p>loose lists</p>
<blockquote class="markdown-alert-note"><p>sink ships</p></blockquote>
<blockquote class="markdown-alert-note"><p>sink ships</p></blockquote>
</li></ul>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0017_l180() {
    let original = r##"  * loose lists

    > [!NOTE]
    - sink ships

    > [!NOTE]
    > - sink ships
"##;
    let expected = r##"<ul><li><p>loose lists</p>
<blockquote class="markdown-alert-note"></blockquote>
<ul><li>sink ships</li></ul>
<blockquote class="markdown-alert-note">
<ul><li>sink ships</li></ul></blockquote>
</li></ul>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn blockquotes_tags_test_0018_l198() {
    let original = r##"> [!Hello]
> This should be a normal block quote.
"##;
    let expected = r##"<blockquote>
<p>[!Hello]
This should be a normal block quote.</p>
</blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}
