// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn cjk_friendly_emphasis_test_1() {
    let original = r##"**このアスタリスクは強調記号として認識されず、そのまま表示されます。**この文のせいで。
"##;
    let expected = r##"<p>**このアスタリスクは強調記号として認識されず、そのまま表示されます。**この文のせいで。</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, false);
}

#[test]
fn cjk_friendly_emphasis_test_2() {
    let original = r##"**このアスタリスクは強調記号として認識されず、そのまま表示されます。**この文のせいで。

**该星号不会被识别，而是直接显示。**这是因为它没有被识别为强调符号。

**이 별표는 강조 표시로 인식되지 않고 그대로 표시됩니다(이 괄호 때문에)**이 문장 때문에.
"##;
    let expected = r##"<p><strong>このアスタリスクは強調記号として認識されず、そのまま表示されます。</strong>この文のせいで。</p>
<p><strong>该星号不会被识别，而是直接显示。</strong>这是因为它没有被识别为强调符号。</p>
<p><strong>이 별표는 강조 표시로 인식되지 않고 그대로 표시됩니다(이 괄호 때문에)</strong>이 문장 때문에.</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn cjk_friendly_emphasis_test_3() {
    let original = r##"これは**私のやりたかったこと。**だからするの。

**[製品ほげ](./product-foo)**と**[製品ふが](./product-bar)**をお試しください

単語と**[単語と](word-and)**単語

**これは太字になりません。**ご注意ください。

カッコに注意**（太字にならない）**文が続く場合に要警戒。

**[リンク](https://example.com)**も注意。（画像も同様）

先頭の**\`コード\`も注意。**

**末尾の\`コード\`**も注意。

税込**¥10,000**で入手できます。

正解は**④**です。

太郎は**「こんにちわ」**といった

太郎は**"こんにちわ"**といった

太郎は**こんにちわ**といった

太郎は**「Hello」**といった

太郎は**"Hello"**といった

太郎は**Hello**といった

太郎は**「Oh my god」**といった

太郎は**"Oh my god"**といった

太郎は**Oh my god**といった

**C#**や**F#**は**「.NET」**というプラットフォーム上で動作します。

IDが**001号**になります。

IDが**００１号**になります。

Go**「初心者」**を対象とした記事です。

**[リンク](https://example.com)**も注意。

**⻲田太郎**と申します

・**㋐**:選択肢１つ目

**真，**她

**真。**她

**真、**她

**真；**她

**真：**她

**真？**她

**真！**她

**真“**她

**真”**她

**真‘**她

**真’**她

**真（**她

真**（她**

**真）**她

**真【**她

真**【她**

**真】**她

**真《**她

真**《她**

**真》**她

**真—**她

**真～**她

**真…**她

**真·**她

**真〃**她

**真-**她

**真々**她

**真**她

**真，** 她

**真**，她

**真，**&ZeroWidthSpace;她

私は**⻲田太郎**と申します

選択肢**㋐**: 1つ目の選択肢

**さようなら︙**と太郎はいった。

.NET**（.NET Frameworkは不可）**では、

「禰󠄀」の偏は示ではなく**礻**です。

Git**（注：不是GitHub）**

太郎は**「こんにちわ」**といった。

𰻞𰻞**（ビャンビャン）**麺

𰻞𰻞**(ビャンビャン)**麺

ハイパーテキストコーヒーポット制御プロトコル**(HTCPCP)**

﨑**(崎)**

国際規格**[ECMA-262](https://tc39.es/ecma262/)**

㐧**(第の俗字)**

𠮟**(こちらが正式表記)**

𪜈**(トモの合略仮名)**

𫠉**(馬の俗字)**

谺𬤲**(こだま)**石神社

石𮧟**(いしただら)**

**推荐几个框架：**React、Vue等前端框架。

葛󠄀**(こちらが正式表記)**城市

禰󠄀**(こちらが正式表記)**豆子

𱟛**(U+317DB)**

阿寒湖アイヌシアターイコㇿ**(Akanko Ainu Theater Ikor)**

あ𛀙**(か)**よろし

𮹝**(simplified form of 龘 in China)**

大塚︀**(U+585A U+FE00)** 大塚**(U+FA10)**

〽︎**(庵点)**は、

**“︁Git”︁**Hub
"##;
    let expected = r##"<p>これは<strong>私のやりたかったこと。</strong>だからするの。</p>
<p><strong><a href="./product-foo">製品ほげ</a></strong>と<strong><a href="./product-bar">製品ふが</a></strong>をお試しください</p>
<p>単語と<strong><a href="word-and">単語と</a></strong>単語</p>
<p><strong>これは太字になりません。</strong>ご注意ください。</p>
<p>カッコに注意<strong>（太字にならない）</strong>文が続く場合に要警戒。</p>
<p><strong><a href="https://example.com">リンク</a></strong>も注意。（画像も同様）</p>
<p>先頭の<strong>`コード`も注意。</strong></p>
<p><strong>末尾の`コード`</strong>も注意。</p>
<p>税込<strong>¥10,000</strong>で入手できます。</p>
<p>正解は<strong>④</strong>です。</p>
<p>太郎は<strong>「こんにちわ」</strong>といった</p>
<p>太郎は<strong>"こんにちわ"</strong>といった</p>
<p>太郎は<strong>こんにちわ</strong>といった</p>
<p>太郎は<strong>「Hello」</strong>といった</p>
<p>太郎は<strong>"Hello"</strong>といった</p>
<p>太郎は<strong>Hello</strong>といった</p>
<p>太郎は<strong>「Oh my god」</strong>といった</p>
<p>太郎は<strong>"Oh my god"</strong>といった</p>
<p>太郎は<strong>Oh my god</strong>といった</p>
<p><strong>C#</strong>や<strong>F#</strong>は<strong>「.NET」</strong>というプラットフォーム上で動作します。</p>
<p>IDが<strong>001号</strong>になります。</p>
<p>IDが<strong>００１号</strong>になります。</p>
<p>Go<strong>「初心者」</strong>を対象とした記事です。</p>
<p><strong><a href="https://example.com">リンク</a></strong>も注意。</p>
<p><strong>⻲田太郎</strong>と申します</p>
<p>・<strong>㋐</strong>:選択肢１つ目</p>
<p><strong>真，</strong>她</p>
<p><strong>真。</strong>她</p>
<p><strong>真、</strong>她</p>
<p><strong>真；</strong>她</p>
<p><strong>真：</strong>她</p>
<p><strong>真？</strong>她</p>
<p><strong>真！</strong>她</p>
<p><strong>真“</strong>她</p>
<p><strong>真”</strong>她</p>
<p><strong>真‘</strong>她</p>
<p><strong>真’</strong>她</p>
<p><strong>真（</strong>她</p>
<p>真<strong>（她</strong></p>
<p><strong>真）</strong>她</p>
<p><strong>真【</strong>她</p>
<p>真<strong>【她</strong></p>
<p><strong>真】</strong>她</p>
<p><strong>真《</strong>她</p>
<p>真<strong>《她</strong></p>
<p><strong>真》</strong>她</p>
<p><strong>真—</strong>她</p>
<p><strong>真～</strong>她</p>
<p><strong>真…</strong>她</p>
<p><strong>真·</strong>她</p>
<p><strong>真〃</strong>她</p>
<p><strong>真-</strong>她</p>
<p><strong>真々</strong>她</p>
<p><strong>真</strong>她</p>
<p><strong>真，</strong> 她</p>
<p><strong>真</strong>，她</p>
<p><strong>真，</strong>​她</p>
<p>私は<strong>⻲田太郎</strong>と申します</p>
<p>選択肢<strong>㋐</strong>: 1つ目の選択肢</p>
<p><strong>さようなら︙</strong>と太郎はいった。</p>
<p>.NET<strong>（.NET Frameworkは不可）</strong>では、</p>
<p>「禰󠄀」の偏は示ではなく<strong>礻</strong>です。</p>
<p>Git<strong>（注：不是GitHub）</strong></p>
<p>太郎は<strong>「こんにちわ」</strong>といった。</p>
<p>𰻞𰻞<strong>（ビャンビャン）</strong>麺</p>
<p>𰻞𰻞<strong>(ビャンビャン)</strong>麺</p>
<p>ハイパーテキストコーヒーポット制御プロトコル<strong>(HTCPCP)</strong></p>
<p>﨑<strong>(崎)</strong></p>
<p>国際規格<strong><a href="https://tc39.es/ecma262/">ECMA-262</a></strong></p>
<p>㐧<strong>(第の俗字)</strong></p>
<p>𠮟<strong>(こちらが正式表記)</strong></p>
<p>𪜈<strong>(トモの合略仮名)</strong></p>
<p>𫠉<strong>(馬の俗字)</strong></p>
<p>谺𬤲<strong>(こだま)</strong>石神社</p>
<p>石𮧟<strong>(いしただら)</strong></p>
<p><strong>推荐几个框架：</strong>React、Vue等前端框架。</p>
<p>葛󠄀<strong>(こちらが正式表記)</strong>城市</p>
<p>禰󠄀<strong>(こちらが正式表記)</strong>豆子</p>
<p>𱟛<strong>(U+317DB)</strong></p>
<p>阿寒湖アイヌシアターイコㇿ<strong>(Akanko Ainu Theater Ikor)</strong></p>
<p>あ𛀙<strong>(か)</strong>よろし</p>
<p>𮹝<strong>(simplified form of 龘 in China)</strong></p>
<p>大塚︀<strong>(U+585A U+FE00)</strong> 大塚<strong>(U+FA10)</strong></p>
<p>〽︎<strong>(庵点)</strong>は、</p>
<p><strong>“︁Git”︁</strong>Hub</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn cjk_friendly_emphasis_test_4() {
    let original = r##"**이 [링크](https://example.kr/)**만을 강조하고 싶다.

**스크립트(script)**라고

패키지를 발행하려면 **`npm publish`**를 실행하십시오.

**안녕(hello)**하세요.

ᅡ**(a)**

**(k)**ᄏ
"##;
    let expected = r##"<p><strong>이 <a href="https://example.kr/">링크</a></strong>만을 강조하고 싶다.</p>
<p><strong>스크립트(script)</strong>라고</p>
<p>패키지를 발행하려면 <strong><code>npm publish</code></strong>를 실행하십시오.</p>
<p><strong>안녕(hello)</strong>하세요.</p>
<p>ᅡ<strong>(a)</strong></p>
<p><strong>(k)</strong>ᄏ</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn cjk_friendly_emphasis_test_5() {
    let original = r##"a**〰**a

a**〽**a

a**🈂**a

a**🈷**a

a**㊗**a

a**㊙**a
"##;
    let expected = r##"<p>a<strong>〰</strong>a</p>
<p>a<strong>〽</strong>a</p>
<p>a<strong>🈂</strong>a</p>
<p>a<strong>🈷</strong>a</p>
<p>a<strong>㊗</strong>a</p>
<p>a<strong>㊙</strong>a</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn cjk_friendly_emphasis_test_6() {
    let original = r##"
a**a«**a

a**»a**a

a**a∇**a

a**∇a**a

a**a𝜵**a

a**𝜵a**a

a**𐬻a**a

a**a𐬻**a
"##;
    let expected = r##"<p>a**a«**a</p>
<p>a**»a**a</p>
<p>a**a∇**a</p>
<p>a**∇a**a</p>
<p>a**a𝜵**a</p>
<p>a**𝜵a**a</p>
<p>a**𐬻a**a</p>
<p>a**a𐬻**a</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn cjk_friendly_emphasis_test_7() {
    let original = r##"__注意__：注意事項

注意：__注意事項__

正體字。︁_Traditional._

正體字。︁__Hong Kong and Taiwan.__

简体字 / 新字体。︀_Simplified._

简体字 / 新字体。︀__Mainland China or Japan.__

“︁Git”︁__Hub__
"##;
    let expected = r##"<p><strong>注意</strong>：注意事項</p>
<p>注意：<strong>注意事項</strong></p>
<p>正體字。︁<em>Traditional.</em></p>
<p>正體字。︁<strong>Hong Kong and Taiwan.</strong></p>
<p>简体字 / 新字体。︀<em>Simplified.</em></p>
<p>简体字 / 新字体。︀<strong>Mainland China or Japan.</strong></p>
<p>“︁Git”︁<strong>Hub</strong></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}
