// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn code_block_attrs_test_1() {
    let original = r##"``` {#ident .class key=value}
xyz
```
"##;
    let expected = r##"<pre id="ident" class="class" data-key="value"><code>xyz
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_2() {
    let original = r##"``` {#mycode .ruby .number-lines}
xyz
```
"##;
    let expected = r##"<pre id="mycode" class="ruby number-lines"><code>xyz
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_3() {
    let original = r##"``` rust {#ident .class}
fn main() {}
```
"##;
    let expected = r##"<pre id="ident" class="class"><code class="language-rust">fn main() {}
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_4() {
    let original = r##"```python {.highlight key=value}
print("hello")
```
"##;
    let expected = r##"<pre class="highlight" data-key="value"><code class="language-python">print("hello")
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_5() {
    let original = r##"``` {#foo} bar
xyz
```
"##;
    let expected = r##"<pre><code class="language-{#foo}">xyz
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_6() {
    let original = r##"```{.class} something
code
```
"##;
    let expected = r##"<pre><code class="language-{.class}">code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_7() {
    let original = r##"```rust{#id}
code
```
"##;
    let expected = r##"<pre><code class="language-rust{#id}">code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_8() {
    let original = r##"```rust {#id}
code
```
"##;
    let expected = r##"<pre id="id"><code class="language-rust">code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_9() {
    let original = r##"~~~ {#ident .class key=value}
xyz
~~~
"##;
    let expected = r##"<pre id="ident" class="class" data-key="value"><code>xyz
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_10() {
    let original = r##"~~~~ruby {#mycode .number-lines}
xyz
~~~~
"##;
    let expected = r##"<pre id="mycode" class="number-lines"><code class="language-ruby">xyz
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_11() {
    let original = r##"``` {key="value with spaces"}
code
```
"##;
    let expected = r##"<pre data-key="value with spaces"><code>code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_12() {
    let original = r##"``` {#id key="multi word value" other=simple}
code
```
"##;
    let expected = r##"<pre id="id" data-key="multi word value" data-other="simple"><code>code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_13() {
    let original = r##"``` {}
code
```
"##;
    let expected = r##"<pre><code>code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_14() {
    let original = r##"``` {   }
code
```
"##;
    let expected = r##"<pre><code>code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_15() {
    let original = r##"```rust
fn main() {}
```
"##;
    let expected = r##"<pre><code class="language-rust">fn main() {}
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_16() {
    let original = r##"```
plain code
```
"##;
    let expected = r##"<pre><code>plain code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_17() {
    let original = r##"``` {key={nested}}
code
```
"##;
    let expected = r##"<pre><code class="language-{key={nested}}">code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_18() {
    let original = r##"``` {key=val\ue}
code
```
"##;
    let expected = r##"<pre><code class="language-{key=val\ue}">code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn code_block_attrs_test_19() {
    let original = r##"``` {key=<value>}
code
```
"##;
    let expected = r##"<pre><code class="language-{key=&lt;value&gt;}">code
</code></pre>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}
