// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn container_extensions_test_0001_l5() {
    let original = r##"> Is this **bold**?
> Is this **bold**?
> ::: spoiler Is this expandable?
> Is this inside?
> :::
"##;
    let expected = r##"<blockquote><p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p>
<details>
<summary>Is this expandable?</summary>
<p>Is this inside?</p>
</details>
</blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0002_l21() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?
> Is this **bold**?
> Is this **bold**?
:::
**is this seperate and bold**
"##;
    let expected = r##"<details>
<summary>Is this expandable?</summary>
<p>Is this collapsable?</p>
<blockquote><p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p></blockquote>
</details>
<p><strong>is this seperate and bold</strong></p>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0003_l38() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?
> Is this **bold**?
> Is this **bold**?
> ::: spoiler Is this expandable?
> Is this inside?
> :::
:::
"##;
    let expected = r##"<details>
<summary>Is this expandable?</summary>
<p>Is this collapsable?</p>
<blockquote><p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p>
<details>
<summary>Is this expandable?</summary>
<p>Is this inside?</p>
</details>
</blockquote>
</details>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0004_l61() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?
> Is this **bold**?
> Is this **bold**?
> ::: spoiler Is this expandable?
> Is this collapsable?
> > Is this **bold**?
> > Is this **bold**?
> :::
:::
**is this seperate and bold**
"##;
    let expected = r##"<details>
<summary>Is this expandable?</summary>
<p>Is this collapsable?</p>
<blockquote><p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p>
<details>
<summary>Is this expandable?</summary>
<p>Is this collapsable?</p>
<blockquote><p>Is this <strong>bold</strong>?
Is this <strong>bold</strong>?</p></blockquote>
</details>
</blockquote>
</details>
<p><strong>is this seperate and bold</strong></p>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0005_l90() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?
:::
**is this seperate and bold**
"##;
    let expected = r##"<details>
<summary>Is this expandable?</summary>
<p>Is this collapsable?</p>
</details>
<p><strong>is this seperate and bold</strong></p>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0006_l103() {
    let original = r##"::: spoiler Is this expandable?
Is this collapsable?

Is this **bold**?
:::
"##;
    let expected = r##"<details>
<summary>Is this expandable?</summary>
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</details>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0007_l117() {
    let original = r##":::spoiler Is this expandable?
Is this collapsable?

Is this **bold**?
:::
"##;
    let expected = r##"<details>
<summary>Is this expandable?</summary>
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</details>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0008_l131() {
    let original = r##"::: example
Is this collapsable?

Is this **bold**?
:::
"##;
    let expected = r##"<div class="example">
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0009_l144() {
    let original = r##":::: example
Is this collapsable?

Is this **bold**?
::::
"##;
    let expected = r##"<div class="example">
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0010_l157() {
    let original = r##":::::spoiler Is this expandable?
Is this collapsable?

Is this **bold**?
:::::
"##;
    let expected = r##"<details>
<summary>Is this expandable?</summary>
<p>Is this collapsable?</p>
<p>Is this <strong>bold</strong>?</p>
</details>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0011_l171() {
    let original = r##":::

content

:::
"##;
    let expected = r##"<p>:::</p>
<p>content</p>
<p>:::</p>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0012_l183() {
    let original = r##"::: block

content

::: end
"##;
    let expected = r##"<div class="block">
<p>content</p>
<div class="end">
</div>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0013_l197() {
    let original = r##" ::: block
:::

::: block
 :::
"##;
    let expected = r##"<div class="block">
</div>
<div class="block">
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0014_l210() {
    let original = r##"::: a
::: b

:::
:::
"##;
    let expected = r##"<div class="a">
<div class="b">
</div>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0015_l223() {
    let original = r##":::: a
::: b

:::
::::
"##;
    let expected = r##"<div class="a">
<div class="b">
</div>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0016_l236() {
    let original = r##"::: a
:::: b

::::
:::
"##;
    let expected = r##"<div class="a">
<div class="b">
</div>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0017_l249() {
    let original = r##":::
Hi
:::
"##;
    let expected = r##"<p>:::
Hi
:::</p>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0018_l259() {
    let original = r##"::::: foo
Hi
:::
::::::
"##;
    let expected = r##"<div class="foo">
<p>Hi
:::</p>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0019_l271() {
    let original = r##"> ::: foo
> Hi
"##;
    let expected = r##"<blockquote>
<div class="foo">
<p>Hi</p>
</div>
</blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0020_l282() {
    let original = r##"::: c_d
Hi
:::
"##;
    let expected = r##"<div class="c_d">
<p>Hi</p>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0021_l292() {
    let original = r##"::: container
> shouldn't close, right?
> :::
> x
:::
"##;
    let expected = r##"<div class="container">
<blockquote>
<p>shouldn't close, right?
:::
x</p>
</blockquote>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0022_l308() {
    let original = r##"::: container
> shouldn't close, right?
> :::
> x

:::
"##;
    let expected = r##"<div class="container">
<blockquote>
<p>shouldn't close, right?
:::
x</p>
</blockquote>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0023_l325() {
    let original = r##"::: a
:::: b
::::: c
::::
x
"##;
    let expected = r##"<div class="a">
<div class="b">
<div class="c">
</div>
</div>
<p>x</p>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0024_l341() {
    let original = r##"::: a
content :::
"##;
    let expected = r##"<div class="a"><p>content :::</p></div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}

#[test]
fn container_extensions_test_0025_l348() {
    let original = r##":::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: a
content :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
"##;
    let expected = r##"<div class="a"><p>content :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::</p></div>
"##;

    test_markdown_html(original, expected, "ENABLE_CONTAINER_EXTENSIONS");
}
