// This file is auto-generated by the build script
// Please, do not modify it manually

#![allow(clippy::field_reassign_with_default)]

use super::{default_opts, test_markdown_html};
use pulldown_cmark::Options;

#[test]
fn gfm_strikethrough_test_1() {
    let original = r##"~~Hi~~ Hello, ~there~ world!
"##;
    let expected = r##"<p><del>Hi</del> Hello, <del>there</del> world!</p>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn gfm_strikethrough_test_2() {
    let original = r##"This ~~has a

new paragraph~~.
"##;
    let expected = r##"<p>This ~~has a</p>
<p>new paragraph~~.</p>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn gfm_strikethrough_test_3() {
    let original = r##"This will ~~~not~~~ strike.
"##;
    let expected = r##"<p>This will ~~~not~~~ strike.</p>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}
