// This file is auto-generated by the build script
// Please, do not modify it manually

#![allow(clippy::field_reassign_with_default)]

use super::{test_markdown_html, TestMarkdownHtmlOptions};

#[test]
fn gfm_strikethrough_test_1() {
    let original = r##"~~Hi~~ Hello, ~there~ world!
"##;
    let expected = r##"<p><del>Hi</del> Hello, <del>there</del> world!</p>
"##;

    let test_opts = TestMarkdownHtmlOptions::default();
    test_markdown_html(original, expected, test_opts);
}

#[test]
fn gfm_strikethrough_test_2() {
    let original = r##"This ~~has a

new paragraph~~.
"##;
    let expected = r##"<p>This ~~has a</p>
<p>new paragraph~~.</p>
"##;

    let test_opts = TestMarkdownHtmlOptions::default();
    test_markdown_html(original, expected, test_opts);
}

#[test]
fn gfm_strikethrough_test_3() {
    let original = r##"This will ~~~not~~~ strike.
"##;
    let expected = r##"<p>This will ~~~not~~~ strike.</p>
"##;

    let test_opts = TestMarkdownHtmlOptions::default();
    test_markdown_html(original, expected, test_opts);
}
