// This file is auto-generated by the build script
// Please, do not modify it manually

#![allow(clippy::field_reassign_with_default)]

use super::{test_markdown_html, TestMarkdownHtmlOptions};

#[test]
fn gfm_tasklist_test_1() {
    let original = r##"- [ ] foo
- [x] bar
"##;
    let expected = r##"<ul>
<li><input disabled="" type="checkbox"/>
foo</li>
<li><input disabled="" type="checkbox" checked=""/>
bar</li>
</ul>
"##;

    let test_opts = TestMarkdownHtmlOptions::default();
    test_markdown_html(original, expected, test_opts);
}

#[test]
fn gfm_tasklist_test_2() {
    let original = r##"- [x] foo
  - [ ] bar
  - [x] baz
- [ ] bim
"##;
    let expected = r##"<ul>
<li><input disabled="" type="checkbox" checked=""/>
foo
<ul>
<li><input disabled="" type="checkbox"/>
bar</li>
<li><input disabled="" type="checkbox" checked=""/>
baz</li>
</ul>
</li>
<li><input disabled="" type="checkbox"/>
bim</li>
</ul>
"##;

    let test_opts = TestMarkdownHtmlOptions::default();
    test_markdown_html(original, expected, test_opts);
}
