// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn highlight_test_1() {
    let original = r##"==hi==
"##;
    let expected = r##"<p><mark>hi</mark></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_2() {
    let original = r##"==hello world==
"##;
    let expected = r##"<p><mark>hello world</mark></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_3() {
    let original = r##"==*hi*==
"##;
    let expected = r##"<p><mark><em>hi</em></mark></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_4() {
    let original = r##"*==hi==*
"##;
    let expected = r##"<p><em><mark>hi</mark></em></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_5() {
    let original = r##"==**bold** and *em*==
"##;
    let expected = r##"<p><mark><strong>bold</strong> and <em>em</em></mark></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_6() {
    let original = r##"=hi=
"##;
    let expected = r##"<p>=hi=</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_7() {
    let original = r##"a = b
"##;
    let expected = r##"<p>a = b</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_8() {
    let original = r##"== hi ==
"##;
    let expected = r##"<p>== hi ==</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_9() {
    let original = r##"==hi ==
"##;
    let expected = r##"<p>==hi ==</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_10() {
    let original = r##"== hi==
"##;
    let expected = r##"<p>== hi==</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_11() {
    let original = r##"===hi===
"##;
    let expected = r##"<p>===hi===</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_12() {
    let original = r##"====hi====
"##;
    let expected = r##"<p>====hi====</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_13() {
    let original = r##"====
"##;
    let expected = r##"<p>====</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_14() {
    let original = r##"a==b==c
"##;
    let expected = r##"<p>a<mark>b</mark>c</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_15() {
    let original = r##"==This==is==highlighted==
"##;
    let expected = r##"<p><mark>This</mark>is<mark>highlighted</mark></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_16() {
    let original = r##"==a
b==
"##;
    let expected = r##"<p><mark>a
b</mark></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_17() {
    let original = r##"==hi \== there==
"##;
    let expected = r##"<p><mark>hi == there</mark></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_18() {
    let original = r##"\==not highlighted==
"##;
    let expected = r##"<p>==not highlighted==</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_19() {
    let original = r##"- ==in a list==
"##;
    let expected = r##"<ul>
<li><mark>in a list</mark></li>
</ul>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_20() {
    let original = r##"> ==in a quote==
"##;
    let expected = r##"<blockquote>
<p><mark>in a quote</mark></p>
</blockquote>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_21() {
    let original = r##"# ==in a heading==
"##;
    let expected = r##"<h1><mark>in a heading</mark></h1>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_22() {
    let original = r##"==~~both~~==
"##;
    let expected = r##"<p><mark><del>both</del></mark></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn highlight_test_23() {
    let original = r##"~~==both==~~
"##;
    let expected = r##"<p><del><mark>both</mark></del></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}
