// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn highlight_test_0001_l8() {
    let original = r##"==hi==
"##;
    let expected = r##"<p><mark>hi</mark></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0002_l14() {
    let original = r##"==hello world==
"##;
    let expected = r##"<p><mark>hello world</mark></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0003_l22() {
    let original = r##"==*hi*==
"##;
    let expected = r##"<p><mark><em>hi</em></mark></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0004_l28() {
    let original = r##"*==hi==*
"##;
    let expected = r##"<p><em><mark>hi</mark></em></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0005_l34() {
    let original = r##"==**bold** and *em*==
"##;
    let expected = r##"<p><mark><strong>bold</strong> and <em>em</em></mark></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0006_l42() {
    let original = r##"=hi=
"##;
    let expected = r##"<p>=hi=</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0007_l48() {
    let original = r##"a = b
"##;
    let expected = r##"<p>a = b</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0008_l56() {
    let original = r##"== hi ==
"##;
    let expected = r##"<p>== hi ==</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0009_l62() {
    let original = r##"==hi ==
"##;
    let expected = r##"<p>==hi ==</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0010_l68() {
    let original = r##"== hi==
"##;
    let expected = r##"<p>== hi==</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0011_l76() {
    let original = r##"===hi===
"##;
    let expected = r##"<p>===hi===</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0012_l82() {
    let original = r##"====hi====
"##;
    let expected = r##"<p>====hi====</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0013_l88() {
    let original = r##"====
"##;
    let expected = r##"<p>====</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0014_l96() {
    let original = r##"a==b==c
"##;
    let expected = r##"<p>a<mark>b</mark>c</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0015_l102() {
    let original = r##"==This==is==highlighted==
"##;
    let expected = r##"<p><mark>This</mark>is<mark>highlighted</mark></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0016_l110() {
    let original = r##"==a
b==
"##;
    let expected = r##"<p><mark>a
b</mark></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0017_l120() {
    let original = r##"==hi \== there==
"##;
    let expected = r##"<p><mark>hi == there</mark></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0018_l126() {
    let original = r##"\==not highlighted==
"##;
    let expected = r##"<p>==not highlighted==</p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0019_l134() {
    let original = r##"- ==in a list==
"##;
    let expected = r##"<ul>
<li><mark>in a list</mark></li>
</ul>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0020_l142() {
    let original = r##"> ==in a quote==
"##;
    let expected = r##"<blockquote>
<p><mark>in a quote</mark></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0021_l150() {
    let original = r##"# ==in a heading==
"##;
    let expected = r##"<h1><mark>in a heading</mark></h1>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT");
}

#[test]
fn highlight_test_0022_l158() {
    let original = r##"==~~both~~==
"##;
    let expected = r##"<p><mark><del>both</del></mark></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT | ENABLE_STRIKETHROUGH");
}

#[test]
fn highlight_test_0023_l164() {
    let original = r##"~~==both==~~
"##;
    let expected = r##"<p><del><mark>both</mark></del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_HIGHLIGHT | ENABLE_STRIKETHROUGH");
}
