// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn inline_link_attrs_test_1() {
    let original = r##"[text](url){#ident .class key=value}
"##;
    let expected = r##"<p><a id="ident" class="class" key="value" href="url">text</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_2() {
    let original = r##"[click here](https://example.com){.btn .primary}
"##;
    let expected = r##"<p><a class="btn primary" href="https://example.com">click here</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_3() {
    let original = r##"![alt text](image.png){#myimg .centered}
"##;
    let expected = r##"<p><img id="myimg" class="centered" src="image.png" alt="alt text" /></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_4() {
    let original = r##"![logo](logo.svg){.logo width=100 height=50}
"##;
    let expected = r##"<p><img class="logo" width="100" height="50" src="logo.svg" alt="logo" /></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_5() {
    let original = r##"[text](url "title"){#id}
"##;
    let expected = r##"<p><a id="id" href="url" title="title">text</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_6() {
    let original = r##"[foo][bar]{.special}

[bar]: /url
"##;
    let expected = r##"<p><a class="special" href="/url">foo</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_7() {
    let original = r##"[example]{#mylink}

[example]: https://example.com
"##;
    let expected = r##"<p><a id="mylink" href="https://example.com">example</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_8() {
    let original = r##"[foo][]{.highlight}

[foo]: /url
"##;
    let expected = r##"<p><a class="highlight" href="/url">foo</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_9() {
    let original = r##"![alt][img]{.responsive}

[img]: photo.jpg
"##;
    let expected = r##"<p><img class="responsive" src="photo.jpg" alt="alt" /></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_10() {
    let original = r##"<https://example.com>{.autolink}
"##;
    let expected = r##"<p><a class="autolink" href="https://example.com">https://example.com</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_11() {
    let original = r##"<user@example.com>{#email .contact}
"##;
    let expected = r##"<p><a id="email" class="contact" href="mailto:user@example.com">user@example.com</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_12() {
    let original = r##"[link](url){#id}{.class}
"##;
    let expected = r##"<p><a id="id" href="url">link</a>{.class}</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_13() {
    let original = r##"[text](url) {#id}
"##;
    let expected = r##"<p><a href="url">text</a> {#id}</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_14() {
    let original = r##"[link](url){title="Link Title" data-info="some info"}
"##;
    let expected = r##"<p><a title="Link Title" data-info="some info" href="url">link</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_15() {
    let original = r##"[link](url){}
"##;
    let expected = r##"<p><a href="url">link</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_16() {
    let original = r##"[normal link](https://example.com)
"##;
    let expected = r##"<p><a href="https://example.com">normal link</a></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}

#[test]
fn inline_link_attrs_test_17() {
    let original = r##"![normal image](photo.jpg)
"##;
    let expected = r##"<p><img src="photo.jpg" alt="normal image" /></p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false);
}
