// This file is auto-generated by the build script
// Please, do not modify it manually

use super::{default_opts, test_markdown_html};
use pulldown_cmark::Options;

#[test]
fn metadata_blocks_test_1() {
    let original = r##"---
title: example
another_field: 0
---
"##;
    let expected = r##""##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_2() {
    let original = r##"---
title: example
another_field: 0
"##;
    let expected = r##"<hr>
<p>title: example
another_field: 0</p>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_3() {
    let original = r##"---
---
"##;
    let expected = r##"<hr>
<hr>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_4() {
    let original = r##"---

title: example
another_field: 0
---
"##;
    let expected = r##"<hr>
<h2>title: example
another_field: 0</h2>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_5() {
    let original = r##"My paragraph here.
---
title: example
another_field: 0
---
"##;
    let expected = r##"<h2>My paragraph here.</h2>
<h2>title: example
another_field: 0</h2>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_6() {
    let original = r##"My paragraph here.

---
title: example
another_field: 0
---
"##;
    let expected = r##"<p>My paragraph here.</p>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_7() {
    let original = r##"---    
title: example
another_field: 0
---

--- -
title: example
another_field: 0
---
"##;
    let expected = r##"<hr>
<h2>title: example
another_field: 0</h2>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_8() {
    let original = r##"---
title: example
another_field: 0
---        

---
title: example
another_field: 0
---a
"##;
    let expected = r##"<hr>
<p>title: example
another_field: 0
---a</p>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_9() {
    let original = r##"---
title: example
another_field: 0
...
"##;
    let expected = r##""##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_10() {
    let original = r##"+++
title: example
another_field: 0
+++
"##;
    let expected = r##""##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_11() {
    let original = r##"    ---
    Things
    ---
"##;
    let expected = r##"<pre><code>---
Things
---
</code></pre>
"##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}

#[test]
fn metadata_blocks_test_12() {
    let original = r##"---
- Item 1
- Item 2
---
"##;
    let expected = r##""##;

    let mut opts = default_opts();
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_YAML_STYLE_METADATA_BLOCKS);
    opts.insert(Options::ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS);
    test_markdown_html(original, expected, opts);
}
