// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn metadata_blocks_test_0001_l22() {
    let original = r##"---
title: example
another_field: 0
---
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0002_l31() {
    let original = r##"---
title: example
another_field: 0
"##;
    let expected = r##"<hr>
<p>title: example
another_field: 0</p>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0003_l42() {
    let original = r##"---
---
"##;
    let expected = r##"<hr>
<hr>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0004_l51() {
    let original = r##"---

title: example
another_field: 0
---
"##;
    let expected = r##"<hr>
<h2>title: example
another_field: 0</h2>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0005_l64() {
    let original = r##"My paragraph here.
---
title: example
another_field: 0
---
"##;
    let expected = r##"<h2>My paragraph here.</h2>
<h2>title: example
another_field: 0</h2>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0006_l77() {
    let original = r##"My paragraph here.

---
title: example
another_field: 0
---
"##;
    let expected = r##"<p>My paragraph here.</p>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0007_l89() {
    let original = r##"---    
title: example
another_field: 0
---

--- -
title: example
another_field: 0
---
"##;
    let expected = r##"<hr>
<h2>title: example
another_field: 0</h2>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0008_l106() {
    let original = r##"---
title: example
another_field: 0
---        

---
title: example
another_field: 0
---a
"##;
    let expected = r##"<hr>
<p>title: example
another_field: 0
---a</p>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0009_l125() {
    let original = r##"---
title: example
another_field: 0
...
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0010_l136() {
    let original = r##"+++
title: example
another_field: 0
+++
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0011_l146() {
    let original = r##"    ---
    Things
    ---
"##;
    let expected = r##"<pre><code>---
Things
---
</code></pre>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}

#[test]
fn metadata_blocks_test_0012_l159() {
    let original = r##"---
- Item 1
- Item 2
---
"##;
    let expected = r##""##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS | ENABLE_PLUSES_DELIMITED_METADATA_BLOCKS");
}
