// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn regression_test_0001_l7() {
    let original = r##"<details><summary>Testing 1..2..3..</summary>

This is a test of the details element.

</details>
"##;
    let expected = r##"<details><summary>Testing 1..2..3..</summary>
<p>This is a test of the details element.</p>
</details>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0002_l21() {
    let original = r##"see the [many] [articles] [on] [QuickCheck].

[many]: https://medium.com/@jlouis666/quickcheck-advice-c357efb4e7e6
[articles]: http://www.quviq.com/products/erlang-quickcheck/
[on]: https://wiki.haskell.org/Introduction_to_QuickCheck1
[QuickCheck]: https://hackage.haskell.org/package/QuickCheck
"##;
    let expected = r##"<p>see the <a href="https://medium.com/@jlouis666/quickcheck-advice-c357efb4e7e6">many</a> <a href="http://www.quviq.com/products/erlang-quickcheck/">articles</a> <a href="https://wiki.haskell.org/Introduction_to_QuickCheck1">on</a> <a href="https://hackage.haskell.org/package/QuickCheck">QuickCheck</a>.</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0003_l34() {
    let original = r##"[![debug-stub-derive on crates.io][cratesio-image]][cratesio]
[![debug-stub-derive on docs.rs][docsrs-image]][docsrs]

[cratesio-image]: https://img.shields.io/crates/v/debug_stub_derive.svg
[cratesio]: https://crates.io/crates/debug_stub_derive
[docsrs-image]: https://docs.rs/debug_stub_derive/badge.svg?version=0.3.0
[docsrs]: https://docs.rs/debug_stub_derive/0.3.0/
"##;
    let expected = r##"<p><a href="https://crates.io/crates/debug_stub_derive"><img src="https://img.shields.io/crates/v/debug_stub_derive.svg" alt="debug-stub-derive on crates.io" /></a>
<a href="https://docs.rs/debug_stub_derive/0.3.0/"><img src="https://docs.rs/debug_stub_derive/badge.svg?version=0.3.0" alt="debug-stub-derive on docs.rs" /></a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0004_l49() {
    let original = r##"|  Title A  |  Title B  |
| --------- | --------- |
| Content   | Content   |

|  Title A  |  Title B  |  Title C  |  Title D  |
| --------- | --------- | --------- | ---------:|
| Content   | Content   | Conent    | Content   |
"##;
    let expected = r##"<table><thead><tr><th>Title A</th><th>Title B</th></tr></thead><tbody>
<tr><td>Content</td><td>Content</td></tr>
</tbody></table>
<table><thead><tr><th>Title A</th><th>Title B</th><th>Title C</th><th style="text-align: right">Title D</th></tr></thead><tbody>
<tr><td>Content</td><td>Content</td><td>Conent</td><td style="text-align: right">Content</td></tr>
</tbody></table>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0005_l68() {
    let original = r##"foo§__(bar)__
"##;
    let expected = r##"<p>foo§<strong>(bar)</strong></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0006_l76() {
    let original = r##"<https://example.com> hello
"##;
    let expected = r##"<p><a href="https://example.com">https://example.com</a> hello</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0007_l84() {
    let original = r##"[foo][bar]

<!-- foo -->
[bar]: a
"##;
    let expected = r##"<p><a href="a">foo</a></p>
<!-- foo -->
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0008_l96() {
    let original = r##"<!-- <dl> -->
- **foo** (u8, u8)

  make something

- **bar** (u16, u16)

  make something
"##;
    let expected = r##"<!-- <dl> -->
<ul>
<li>
<p><strong>foo</strong> (u8, u8)</p>
<p>make something</p>
</li>
<li>
<p><strong>bar</strong> (u16, u16)</p>
<p>make something</p>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0009_l121() {
    let original = r##"[`
i8
`](
../../../std/primitive.i8.html
)
"##;
    let expected = r##"<p><a href="../../../std/primitive.i8.html"><code>i8</code></a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0010_l133() {
    let original = r##"[a]

[a]: /url (title\\*)
"##;
    let expected = r##"<p><a href="/url" title="title\*">a</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0011_l141() {
    let original = r##"[a]

[a]: /url (title\))
"##;
    let expected = r##"<p><a href="/url" title="title)">a</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0012_l149() {
    let original = r##"[a]

[a]: /url (title))
"##;
    let expected = r##"<p>[a]</p>
<p>[a]: /url (title))</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0013_l160() {
    let original = r##"a <?php this is not a valid processing tag
---
b <?php but this is ?>
"##;
    let expected = r##"<h2>a &lt;?php this is not a valid processing tag</h2>
<p>b <?php but this is ?></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0014_l171() {
    let original = r##"[a]: u\
foo
"##;
    let expected = r##"<p>foo</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0015_l180() {
    let original = r##"\`foo`
"##;
    let expected = r##"<p>`foo`</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0016_l188() {
    let original = r##"foo\\
bar
"##;
    let expected = r##"<p>foo\
bar</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0017_l198() {
    let original = r##"1\. foo

1\) bar
"##;
    let expected = r##"<p>1. foo</p>
<p>1) bar</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0018_l209() {
    let original = r##"1...

1.2.3.

1 2 3 .

1.|2.-3.

1)2)3)
"##;
    let expected = r##"<p>1...</p>
<p>1.2.3.</p>
<p>1 2 3 .</p>
<p>1.|2.-3.</p>
<p>1)2)3)</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0019_l229() {
    let original = r##"[](<<>)
"##;
    let expected = r##"<p>[](&lt;&lt;&gt;)</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0020_l237() {
    let original = r##"\``foo``bar`
"##;
    let expected = r##"<p>`<code>foo``bar</code></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0021_l245() {
    let original = r##"\\`foo`
"##;
    let expected = r##"<p>\<code>foo</code></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0022_l253() {
    let original = r##"[\\]: x

YOLO
"##;
    let expected = r##"<p>YOLO</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0023_l263() {
    let original = r##"lorem ipsum
A | B
---|---
foo | bar
"##;
    let expected = r##"<p>lorem ipsum
A | B
---|---
foo | bar</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0024_l277() {
    let original = r##"foo|bar  
---|---
foo|bar
"##;
    let expected = r##"<table><thead><tr><th>foo</th><th>bar</th></tr></thead>
<tbody><tr><td>foo</td><td>bar</td></tr></tbody>
</table>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0025_l289() {
    let original = r##"foo|bar\\
---|---
foo|bar
"##;
    let expected = r##"<table><thead><tr><th>foo</th><th>bar\</th></tr></thead>
<tbody><tr><td>foo</td><td>bar</td></tr></tbody>
</table>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0026_l301() {
    let original = r##"[<foo>](url)
"##;
    let expected = r##"<p><a href="url"><foo></a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0027_l309() {
    let original = r##"[<foo>bar</foo>](url)
"##;
    let expected = r##"<p><a href="url"><foo>bar</foo></a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0028_l317() {
    let original = r##"![<http://example.com>](http://example.com/logo.png)
"##;
    let expected = r##"<p><img src="http://example.com/logo.png" alt="http://example.com" /></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0029_l325() {
    let original = r##"[<http://one> <http://two>](url)
"##;
    let expected = r##"<p><a href="url"><a href="http://one">http://one</a> <a href="http://two">http://two</a></a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0030_l333() {
    let original = r##"Markdown | Less | Pretty
--- | --- | ---
 
some text
"##;
    let expected = r##"<table><thead><tr><th>Markdown</th><th>Less</th><th>Pretty</th></tr></thead><tbody>
</tbody></table>
<p>some text</p>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0031_l346() {
    let original = r##"1. > foo
2. >
"##;
    let expected = r##"<ol>
<li>
<blockquote>
<p>foo</p>
</blockquote>
</li>
<li>
<blockquote>
</blockquote>
</li>
</ol>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0032_l365() {
    let original = r##"[
x

]: f
"##;
    let expected = r##"<p>[
x</p>
<p>]: f</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0033_l378() {
    let original = r##"[foo]:
"##;
    let expected = r##"<p>[foo]:</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0034_l386() {
    let original = r##"> [foo
> bar]: /url
>
> [foo bar]
"##;
    let expected = r##"<blockquote>
<p><a href="/url">foo bar</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0035_l399() {
    let original = r##"> foo | bar
> --- | ---
yolo | swag
"##;
    let expected = r##"<blockquote>
<table><thead><tr><th>foo</th><th>bar</th></tr></thead><tbody></tbody></table>
</blockquote>
<p>yolo | swag</p>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0036_l412() {
    let original = r##"<foo bar>
"##;
    let expected = r##"<foo bar>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0037_l420() {
    let original = r##"<foo bar =
 "hi"> 
"##;
    let expected = r##"<p><foo bar =
 "hi"></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0038_l430() {
    let original = r##"~~*_**__

__a__
"##;
    let expected = r##"<p>~~*_**__</p>
<p><strong>a</strong></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0039_l441() {
    let original = r##"> `
> `
"##;
    let expected = r##"<blockquote>
<p><code> </code></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0040_l452() {
    let original = r##"`\|`
"##;
    let expected = r##"<p><code>\|</code></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0041_l460() {
    let original = r##"Paragraph 1
    
Paragraph 2
"##;
    let expected = r##"<p>Paragraph 1</p>
<p>Paragraph 2</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0042_l471() {
    let original = r##"\[[link text](https://www.google.com/)\]
"##;
    let expected = r##"<p>[<a href="https://www.google.com/">link text</a>]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0043_l479() {
    let original = r##"foo | bar
--- | ---
[a](< | url>)
"##;
    let expected = r##"<table><thead><tr><th>foo</th><th>bar</th></tr></thead><tbody><tr><td>[a](&lt;</td><td>url&gt;)</td></tr></tbody></table>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0044_l489() {
    let original = r##"[a](url "
- - -
")
"##;
    let expected = r##"<p>[a](url "</p>
<hr>
<p>")</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0045_l501() {
    let original = r##"[a](url

)
"##;
    let expected = r##"<p>[a](url</p>
<p>)</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0046_l512() {
    let original = r##"[a](b "

")
"##;
    let expected = r##"<p>[a](b "</p>
<p>")</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0047_l523() {
    let original = r##"<http:// >
"##;
    let expected = r##"<p>&lt;http:// &gt;</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0048_l531() {
    let original = r##"<http://>
"##;
    let expected = r##"<p>&lt;http://&gt;</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0049_l539() {
    let original = r##"foo | bar
--- | ---
<http://| baz
"##;
    let expected = r##"<table>
<thead>
<tr><th>foo</th><th>bar</th></tr>
</thead>
<tbody>
<tr><td>&lt;http://</td><td>baz</td></tr>
</tbody>
</table>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0050_l556() {
    let original = r##"foo | bar
--- | ---
<http://|>
"##;
    let expected = r##"<table>
<thead>
<tr><th>foo</th><th>bar</th></tr>
</thead>
<tbody>
<tr><td>&lt;http://</td><td>&gt;</td></tr>
</tbody>
</table>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0051_l573() {
    let original = r##"<sup>\*hi</sup>\_
"##;
    let expected = r##"<p><sup>*hi</sup>_</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0052_l581() {
    let original = r##"email: <john@example.com>\_
"##;
    let expected = r##"<p>email: <a href="mailto:john@example.com">john@example.com</a>_</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0053_l589() {
    let original = r##"> [link](/url 'foo
> bar')
"##;
    let expected = r##"<blockquote>
<p><a href="/url" title="foo
bar">link</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0054_l601() {
    let original = r##"> [foo
> bar]: /url
>
> [foo bar]
"##;
    let expected = r##"<blockquote>
<p><a href="/url">foo bar</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0055_l614() {
    let original = r##"> [foo   bar]: /url
>
> [foo
> bar]
"##;
    let expected = r##"<blockquote>
<p><a href="/url">foo
bar</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0056_l628() {
    let original = r##"> - [a
> b c]: /foo

[a b c]
"##;
    let expected = r##"<blockquote>
<ul>
<li></li>
</ul>
</blockquote>
<p><a href="/foo">a b c</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0057_l644() {
    let original = r##"[a
> b]: /foo

[a b] [a > b]
"##;
    let expected = r##"<p>[a</p>
<blockquote>
<p>b]: /foo</p>
</blockquote>
<p>[a b] [a &gt; b]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0058_l659() {
    let original = r##"[`cargo
package`]

[`cargo package`]: https://example.com
"##;
    let expected = r##"<p><a href="https://example.com"><code>cargo package</code></a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0059_l670() {
    let original = r##"> [`cargo
> package`]

[`cargo package`]: https://example.com
"##;
    let expected = r##"<blockquote>
<p><a href="https://example.com"><code>cargo package</code></a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0060_l683() {
    let original = r##"> `cargo
> package`
"##;
    let expected = r##"<blockquote>
<p><code>cargo package</code></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0061_l694() {
    let original = r##"> Note: Though you should not rely on this, all pointers to <abbr
> title="Dynamically Sized Types">DSTs</abbr> are currently twice the size of
> the size of `usize` and have the same alignment.
"##;
    let expected = r##"<blockquote>
<p>Note: Though you should not rely on this, all pointers to <abbr
title="Dynamically Sized Types">DSTs</abbr> are currently twice the size of
the size of <code>usize</code> and have the same alignment.</p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0062_l708() {
    let original = r##"Lorem ipsum.[^a]

An unordered list before the footnotes:
* Ipsum
* Lorem

[^a]: Cool.
"##;
    let expected = r##"<p>Lorem ipsum.<sup class="footnote-reference"><a href="#a">1</a></sup></p>
<p>An unordered list before the footnotes:</p>
<ul>
<li>Ipsum</li>
<li>Lorem</li>
</ul>
<div class="footnote-definition" id="a"><sup class="footnote-definition-label">1</sup>
<p>Cool.</p>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_FOOTNOTES");
}

#[test]
fn regression_test_0063_l730() {
    let original = r##"[][a]

[a]: b

# assimp-rs [![][crates-badge]][crates]

[crates]: https://crates.io/crates/assimp
[crates-badge]: http://meritbadge.herokuapp.com/assimp
"##;
    let expected = r##"<p><a href="b"></a></p>
<h1>assimp-rs <a href="https://crates.io/crates/assimp"><img src="http://meritbadge.herokuapp.com/assimp" alt="" /></a></h1>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0064_l746() {
    let original = r##"* A list.

   * A sublist.

   * Another sublist.


* A list.
 
   * A sublist.
 
   * Another sublist.
 
"##;
    let expected = r##"<ul>
<li>
<p>A list.</p>
<ul>
<li>
<p>A sublist.</p>
</li>
<li>
<p>Another sublist.</p>
</li>
</ul>
</li>
<li>
<p>A list.</p>
<ul>
<li>
<p>A sublist.</p>
</li>
<li>
<p>Another sublist.</p>
</li>
</ul>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0065_l789() {
    let original = r##"<foo
"##;
    let expected = r##"<p>&lt;foo</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0066_l797() {
    let original = r##"> > a <a href
> > ="yo
> > lo">
"##;
    let expected = r##"<blockquote>
<blockquote>
<p>a <a href
="yo
lo"></p>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0067_l813() {
    let original = r##"	-	the whitespace here are tabs
"##;
    let expected = r##"<pre><code>-	the whitespace here are tabs
</code></pre>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0068_l822() {
    let original = r##"1. a
   1. a

a
2. a
"##;
    let expected = r##"<ol>
<li>a
<ol>
<li>a</li>
</ol>
</li>
</ol>
<p>a
2. a</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0069_l842() {
    let original = r##"1. a
2. a
   2. a
"##;
    let expected = r##"<ol>
<li>a</li>
<li>a
2. a</li>
</ol>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0070_l856() {
    let original = r##"* [ ] foo

* [ ] bar

baz
"##;
    let expected = r##"<ul>
<li><p><input disabled="" type="checkbox"/>
foo</p></li><li><p><input disabled="" type="checkbox"/>
bar</p></li>
</ul>
<p>baz</p>
"##;

    test_markdown_html(original, expected, "ENABLE_TASKLISTS");
}

#[test]
fn regression_test_0071_l873() {
    let original = r##"* foo
    + bar
    + baz
"##;
    let expected = r##"<ul>
<li>foo
<ul>
<li>bar</li>
<li>baz</li>
</ul>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0072_l890() {
    let original = r##"[`]: xx:

[`]`]
"##;
    let expected = r##"<p>[<code>]</code>]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0073_l900() {
    let original = r##"~~foo~~bar
"##;
    let expected = r##"<p><del>foo</del>bar</p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0074_l906() {
    let original = r##"foo~~bar~~
"##;
    let expected = r##"<p>foo<del>bar</del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0075_l914() {
    let original = r##"*~~__emphasis strike strong__~~* ~~*__strike emphasis strong__*~~
"##;
    let expected = r##"<p><em><del><strong>emphasis strike strong</strong></del></em> <del><em><strong>strike emphasis strong</strong></em></del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0076_l920() {
    let original = r##"*~~__emphasis strike strong__~~* ~~*__`strike emphasis strong code`__*~~
"##;
    let expected = r##"<p><em><del><strong>emphasis strike strong</strong></del></em> <del><em><strong><code>strike emphasis strong code</code></strong></em></del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0077_l926() {
    let original = r##"*~~`emphasis strike code`~~* ~~*__strike emphasis strong__*~~
"##;
    let expected = r##"<p><em><del><code>emphasis strike code</code></del></em> <del><em><strong>strike emphasis strong</strong></em></del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0078_l932() {
    let original = r##"*~~`emphasis strike code`~~* ~~*__`strike emphasis strong code`__*~~
"##;
    let expected = r##"<p><em><del><code>emphasis strike code</code></del></em> <del><em><strong><code>strike emphasis strong code</code></strong></em></del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0079_l938() {
    let original = r##"**~~_strong strike emphasis_~~** ~~*__strike emphasis strong__*~~
"##;
    let expected = r##"<p><strong><del><em>strong strike emphasis</em></del></strong> <del><em><strong>strike emphasis strong</strong></em></del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0080_l944() {
    let original = r##"**~~_strong strike emphasis_~~** ~~*__`strike emphasis strong code`__*~~
"##;
    let expected = r##"<p><strong><del><em>strong strike emphasis</em></del></strong> <del><em><strong><code>strike emphasis strong code</code></strong></em></del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0081_l950() {
    let original = r##"**~~`strong strike code`~~** ~~*__strike emphasis strong__*~~
"##;
    let expected = r##"<p><strong><del><code>strong strike code</code></del></strong> <del><em><strong>strike emphasis strong</strong></em></del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0082_l956() {
    let original = r##"**~~`strong strike code`~~** ~~*__`strike emphasis strong code`__*~~
"##;
    let expected = r##"<p><strong><del><code>strong strike code</code></del></strong> <del><em><strong><code>strike emphasis strong code</code></strong></em></del></p>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0083_l964() {
    let original = r##"  | foo | bar  |
  |-----|------|
  | baz | alef |

  | foo | bar  |
  |-----|------|
| baz | alef |

  | foo | bar  |
|-----|------|
  | baz | alef |

| foo | bar  |
  |-----|------|
  | baz | alef |

  | foo | bar  |
|-----|------|
| baz | alef |

| foo | bar  |
|-----|------|
  | baz | alef |

| foo | bar  |
|-----|------|
| baz | alef |

| foo | bar  |
  |-----|------|
| baz | alef |

    | foo | bar  |
    |-----|------|
    | baz | alef |

| foo | bar  |
    |-----|------|
| baz | alef |

	| foo | bar  |
	|-----|------|
	| baz | alef |

| foo | bar  |
	|-----|------|
| baz | alef |
"##;
    let expected = r##"<table><thead><tr><th>foo</th><th>bar</th></tr></thead>
<tbody><tr><td>baz</td><td>alef</td></tr></tbody>
</table>
<table><thead><tr><th>foo</th><th>bar</th></tr></thead>
<tbody><tr><td>baz</td><td>alef</td></tr></tbody>
</table>
<table><thead><tr><th>foo</th><th>bar</th></tr></thead>
<tbody><tr><td>baz</td><td>alef</td></tr></tbody>
</table>
<table><thead><tr><th>foo</th><th>bar</th></tr></thead>
<tbody><tr><td>baz</td><td>alef</td></tr></tbody>
</table>
<table><thead><tr><th>foo</th><th>bar</th></tr></thead>
<tbody><tr><td>baz</td><td>alef</td></tr></tbody>
</table>
<table><thead><tr><th>foo</th><th>bar</th></tr></thead>
<tbody><tr><td>baz</td><td>alef</td></tr></tbody>
</table>
<table><thead><tr><th>foo</th><th>bar</th></tr></thead>
<tbody><tr><td>baz</td><td>alef</td></tr></tbody>
</table>
<table><thead><tr><th>foo</th><th>bar</th></tr></thead>
<tbody><tr><td>baz</td><td>alef</td></tr></tbody>
</table>
<pre><code>| foo | bar  |
|-----|------|
| baz | alef |
</code></pre>
<p>| foo | bar  |
|-----|------|
| baz | alef |</p>
<pre><code>| foo | bar  |
|-----|------|
| baz | alef |
</code></pre>
<p>| foo | bar  |
|-----|------|
| baz | alef |</p>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0084_l1056() {
    let original = r##"### ###
"##;
    let expected = r##"<h3></h3>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0085_l1062() {
    let original = r##"### 
"##;
    let expected = r##"<h3></h3>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0086_l1072() {
    let original = r##"<!doctype html>
"##;
    let expected = r##"<!doctype html>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0087_l1081() {
    let original = r##"| A | table    |
| ------ | ---- |
| not   |  in  |
| a     | list|

* A blockquote:
  > inside a list item
* A Heading:
  # inside a list item
* A table:

  | inside | a       |
  | ------ | ------- |
  | list   | item    |
  | with   | leading |
  | empty  | lines   |
* A table:
  | inside  | a       |
  | ------- | ------- |
  | list    | item    |
  | without | leading |
  | empty   | lines   |
"##;
    let expected = r##"<table><thead><tr><th>A</th><th>table</th></tr></thead><tbody>
<tr><td>not</td><td>in</td></tr>
<tr><td>a</td><td>list</td></tr>
</tbody></table>
<ul>
<li>
<p>A blockquote:</p>
<blockquote>
<p>inside a list item</p>
</blockquote>
</li>
<li>
<p>A Heading:</p>
<h1>inside a list item</h1>
</li>
<li>
<p>A table:</p>
<table><thead><tr><th>inside</th><th>a</th></tr></thead><tbody>
<tr><td>list</td><td>item</td></tr>
<tr><td>with</td><td>leading</td></tr>
<tr><td>empty</td><td>lines</td></tr>
</tbody></table>
</li>
<li>
<p>A table:</p>
<table><thead><tr><th>inside</th><th>a</th></tr></thead><tbody>
<tr><td>list</td><td>item</td></tr>
<tr><td>without</td><td>leading</td></tr>
<tr><td>empty</td><td>lines</td></tr>
</tbody></table>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0088_l1142() {
    let original = r##"a\

b
"##;
    let expected = r##"<p>a\</p>
<p>b</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0089_l1151() {
    let original = r##"a\
* b
"##;
    let expected = r##"<p>a\</p>
<ul>
<li>b</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0090_l1161() {
    let original = r##"a\
> b
"##;
    let expected = r##"<p>a\</p>
<blockquote>
<p>b</p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0091_l1171() {
    let original = r##"a\
# b
"##;
    let expected = r##"<p>a\</p>
<h1>b</h1>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0092_l1179() {
    let original = r##"a\
==
"##;
    let expected = r##"<h1>a\</h1>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0093_l1186() {
    let original = r##"> a\
>
"##;
    let expected = r##"<blockquote>
<p>a\</p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0094_l1198() {
    let original = r##"<a
>
"##;
    let expected = r##"<p>&lt;a</p>
<blockquote></blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0095_l1206() {
    let original = r##"<div
>
"##;
    let expected = r##"<div
>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0096_l1214() {
    let original = r##"<a
> quote
"##;
    let expected = r##"<p>&lt;a</p>
<blockquote><p>quote</p></blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0097_l1222() {
    let original = r##"<div
> not quote
"##;
    let expected = r##"<div
> not quote
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0098_l1230() {
    let original = r##"<a
>quote
"##;
    let expected = r##"<p>&lt;a</p>
<blockquote><p>quote</p></blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0099_l1238() {
    let original = r##"<div
>not quote
"##;
    let expected = r##"<div
>not quote
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0100_l1248() {
    let original = r##"> alpha
> | a | b |
> |---|---|
> | c | d |
"##;
    let expected = r##"<blockquote>
<p>alpha</p>
<table>
<thead><tr><th>a</th><th>b</th></tr></thead><tbody>
<tr><td>c</td><td>d</td></tr>
</tbody></table>
</blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0101_l1266() {
    let original = r##"***R]*-*
"##;
    let expected = r##"<p>*<em><em>R]</em>-</em></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0102_l1272() {
    let original = r##"****foo*bar*baz****
"##;
    let expected = r##"<p><strong><em><em>foo</em>bar</em>baz</strong>**</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0103_l1281() {
    let original = r##";
*
%
"##;
    let expected = r##"<p>;
*
%</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0104_l1293() {
    let original = r##";
* 
%
"##;
    let expected = r##"<p>;
*
%</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0105_l1306() {
    let original = r##"<@1>
"##;
    let expected = r##"<p>&lt;@1&gt;</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0106_l1315() {
    let original = r##"---
anything:
    indented4Spaces: true
---
Things
"##;
    let expected = r##"<p>Things</p>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS");
}

#[test]
fn regression_test_0107_l1325() {
    let original = r##"---
something:
  nested:
    twice: true
---
Things
"##;
    let expected = r##"<p>Things</p>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS");
}

#[test]
fn regression_test_0108_l1336() {
    let original = r##"---
lists:
    - indented 4 spaces
---
Things
"##;
    let expected = r##"<p>Things</p>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS");
}

#[test]
fn regression_test_0109_l1348() {
    let original = r##"-

-


-



-
"##;
    let expected = r##"<ul>
<li></li>
<li></li>
<li></li>
<li></li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0110_l1368() {
    let original = r##"-

  -  .
"##;
    let expected = r##"<ul>
<li></li>
<li><p>.</p></li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0111_l1381() {
    let original = r##"j***5*=*
"##;
    let expected = r##"<p>j*<em><em>5</em>=</em></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0112_l1390() {
    let original = r##"Not enough table

|
|

Not enough table

|x
|

Not enough table

|
|-

Table

|x
|-

Not enough table
| col1 | col2 |
|      | ---- |

Not enough table
| col1 | col2 |
| :    | ---- |

Table
| col1 | col2 |
| ---- | ---- |
"##;
    let expected = r##"<p>Not enough table</p>
<p>|
|</p>
<p>Not enough table</p>
<p>|x
|</p>
<p>Not enough table</p>
<p>|
|-</p>
<p>Table</p>
<table>
<thead><tr><th>x</th></tr></thead>
<tbody>
</tbody>
</table>
<p>Not enough table
| col1 | col2 |
|      | ---- |</p>
<p>Not enough table
| col1 | col2 |
| :    | ---- |</p>
<p>Table</p>
<table>
<thead><tr><th>col1</th><th>col2</th></tr></thead>
<tbody>
</tbody>
</table>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0113_l1454() {
    let original = r##"[x] is not a valid link definition, because parens aren't balanced.

[x]: (
"##;
    let expected = r##"<p>[x] is not a valid link definition, because parens aren't balanced.</p>
<p>[x]: (</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0114_l1465() {
    let original = r##"Both of these two paragraphs are structurally the same, but the first one has
an unmatched asterisk.

_*_
*{*{

_x_
*{*{
"##;
    let expected = r##"<p>Both of these two paragraphs are structurally the same, but the first one has
an unmatched asterisk.</p>
<p><em>*</em>
<em>{</em>{</p>
<p><em>x</em>
<em>{</em>{</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0115_l1485() {
    let original = r##"**a.*.**a*.**.
"##;
    let expected = r##"<p>*<em>a.*.<em><em>a</em>.</em></em>.</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0116_l1493() {
    let original = r##"_*__*_*

_*xx*_*

_*__-_-

_*xx-_-
"##;
    let expected = r##"<p><em><em>__</em></em>*</p>
<p><em><em>xx</em></em>*</p>
<p><em>*__-</em>-</p>
<p><em>*xx-</em>-</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0117_l1511() {
    let original = r##"-

	-


- x

	-
"##;
    let expected = r##"<ul>
<li></li>
</ul>
<pre><code>-
</code></pre>
<ul>
<li>
<p>x</p>
<ul>
<li></li>
</ul>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0118_l1536() {
    let original = r##"-

    -


- x

    -
"##;
    let expected = r##"<ul>
<li></li>
</ul>
<pre><code>-
</code></pre>
<ul>
<li>
<p>x</p>
<ul>
<li></li>
</ul>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0119_l1563() {
    let original = r##"[x\

]: https://rust-lang.org
"##;
    let expected = r##"<p>[x\</p>
<p>]: https://rust-lang.org</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0120_l1574() {
    let original = r##">>**#*
>
>**#*

**#*

|**#*|
|----|
|**#*|
|**#*
**#*|
**#*
"##;
    let expected = r##"<blockquote>
<blockquote>
<p>*<em>#</em></p>
</blockquote>
<p>*<em>#</em></p>
</blockquote>
<p>*<em>#</em></p>
<table><thead><tr><th>*<em>#</em></th></tr></thead><tbody>
<tr><td>*<em>#</em></td></tr>
<tr><td>*<em>#</em></td></tr>
<tr><td>*<em>#</em></td></tr>
<tr><td>*<em>#</em></td></tr>
</tbody></table>
"##;

    test_markdown_html(original, expected, "ENABLE_TABLES");
}

#[test]
fn regression_test_0121_l1605() {
    let original = r##"The second hyphen should parse the same way in both samples.

 - >*

   -

The second hyphen should parse the same way in both samples.

 - >x

   -
"##;
    let expected = r##"<p>The second hyphen should parse the same way in both samples.</p>
<ul>
<li>
<blockquote>
<ul>
<li></li>
</ul>
</blockquote>
<ul>
<li></li>
</ul>
</li>
</ul>
<p>The second hyphen should parse the same way in both samples.</p>
<ul>
<li>
<blockquote>
<p>x</p>
</blockquote>
<ul>
<li></li>
</ul>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0122_l1647() {
    let original = r##"> Rewriting it in [Rust] is usually a bad idea.
>
> [Rust]:
https://rust-lang.org
"##;
    let expected = r##"<blockquote>
<p>Rewriting it in <a href="https://rust-lang.org">Rust</a> is usually a bad idea.</p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0123_l1660() {
    let original = r##"[First try
----------
Second try]: https://rust-lang.org
"##;
    let expected = r##"<h2>[First try</h2>
<p>Second try]: https://rust-lang.org</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0124_l1671() {
    let original = r##"[^foo][]

[^foo][baz]

[baz][^foo]

[^foo]: bar

[baz]: https://rust-lang.org
"##;
    let expected = r##"<p><sup class="footnote-reference"><a href="#foo">1</a></sup>[]</p>
<p><a href="https://rust-lang.org">^foo</a></p>
<p><a href="https://rust-lang.org">baz</a><sup class="footnote-reference"><a href="#foo">1</a></sup></p>
<div class="footnote-definition" id="foo"><sup class="footnote-definition-label">1</sup>
<p>bar</p>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_FOOTNOTES");
}

#[test]
fn regression_test_0125_l1692() {
    let original = r##"# foo \
bar \
"##;
    let expected = r##"<h1>foo \</h1>
<p>bar \</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0126_l1702() {
    let original = r##"[third try]:
-

[third try]
"##;
    let expected = r##"<h2>[third try]:</h2>
<p>[third try]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0127_l1715() {
    let original = r##"- [foo]: test
bar

> [bar]: test
[baz]: rstr
[bar]
"##;
    let expected = r##"<ul>
<li>bar</li>
</ul>
<blockquote>
<p><a href="test">bar</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0128_l1731() {
    let original = r##"> - [foo]: test
> bar
> 
> > [bar]: test
> [baz]: rstr
> [bar]
"##;
    let expected = r##"<blockquote>
<ul>
<li>bar</li>
</ul>
<blockquote>
<p><a href="test">bar</a></p>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0129_l1749() {
    let original = r##"[bar]: test
-
"##;
    let expected = r##"<p>-</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0130_l1758() {
    let original = r##"[link](
foo)

> [link](
> foo)
"##;
    let expected = r##"<p><a href="foo">link</a></p>
<blockquote>
<p><a href="foo">link</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0131_l1771() {
    let original = r##"[link](foo
)

> [link](foo
> )
"##;
    let expected = r##"<p><a href="foo">link</a></p>
<blockquote>
<p><a href="foo">link</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0132_l1784() {
    let original = r##"[link](foo
"bar"
)

> [link](foo
> "bar"
> )
"##;
    let expected = r##"<p><a href="foo" title="bar">link</a></p>
<blockquote>
<p><a href="foo" title="bar">link</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0133_l1799() {
    let original = r##"[link](	
	foo	
	"bar"	
	)

> [link](	
> 	foo	
> 	"bar"	
> 	)
"##;
    let expected = r##"<p><a href="foo" title="bar">link</a></p>
<blockquote>
<p><a href="foo" title="bar">link</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0134_l1816() {
    let original = r##"[linkme]: foo
    - baz
"##;
    let expected = r##"<p>- baz</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0135_l1825() {
    let original = r##"[linkme-3]:
   [^foo]:

[linkme-4]:
    [^bar]:

GFM footnotes can interrupt link defs if they have three spaces, but not four.
"##;
    let expected = r##"<p>[linkme-3]:</p>
<div class="footnote-definition" id="foo"><sup class="footnote-definition-label">1</sup></div>
<p>GFM footnotes can interrupt link defs if they have three spaces, but not four.</p>
"##;

    test_markdown_html(original, expected, "ENABLE_FOOTNOTES");
}

#[test]
fn regression_test_0136_l1839() {
    let original = r##"[linkme-3]:
   ===

[linkme-4]:
    ===

Setext heading can interrupt link def if it has three spaces, but not four.
"##;
    let expected = r##"<h1>[linkme-3]:</h1>
<p>Setext heading can interrupt link def if it has three spaces, but not four.</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0137_l1852() {
    let original = r##"[linkme-3]: a
   - a

[linkme-4]: a
    - b

List can interrupt the paragraph at the start of a link definition if it starts with three spaces, but not four.
"##;
    let expected = r##"<ul>
<li>a</li>
</ul>
<p>- b</p>
<p>List can interrupt the paragraph at the start of a link definition if it starts with three spaces, but not four.</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0138_l1871() {
    let original = r##"[first
-
second]: https://example.com

[first
-
second]
"##;
    let expected = r##"<h2>[first</h2>
<p>second]: https://example.com</p>
<h2>[first</h2>
<p>second]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0139_l1886() {
    let original = r##"[first
    -
second]: https://example.com

[first
    -
second]
"##;
    let expected = r##"<p><a href="https://example.com">first
-
second</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0140_l1900() {
    let original = r##"[first]: https://example.com
"
-
"

[first]
"##;
    let expected = r##"<h2>"</h2>
<p>"</p>
<p><a href="https://example.com">first</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0141_l1913() {
    let original = r##"[first]: https://example.com
"
    -
"

[first]
"##;
    let expected = r##"<p><a href="https://example.com" title="
-
">first</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0142_l1926() {
    let original = r##"> [first]: https://example.com
> "
> -
> "
>
> [first]
"##;
    let expected = r##"<blockquote>
<h2>"</h2>
<p>"</p>
<p><a href="https://example.com">first</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0143_l1943() {
    let original = r##"> ```
> code

> text
"##;
    let expected = r##"<blockquote>
<pre><code>code
</code></pre>
</blockquote>
<blockquote>
<p>text</p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0144_l1958() {
    let original = r##"> [first]: https://example.com
> "
>     -
> "
>
> [first]
"##;
    let expected = r##"<blockquote>
<p><a href="https://example.com" title="
-
">first</a></p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0145_l1973() {
    let original = r##"[first]: https://example.com
"
\
"

[first]
"##;
    let expected = r##"<p><a href="https://example.com" title="
\
">first</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0146_l1986() {
    let original = r##"[first]: https://example.com
"
\

"

[first]
"##;
    let expected = r##"<p>"
\</p>
<p>"</p>
<p><a href="https://example.com">first</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0147_l2004() {
    let original = r##"[foo]: https://example.com
'[foo]'bar
"##;
    let expected = r##"<p>'<a href="https://example.com">foo</a>'bar</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0148_l2011() {
    let original = r##"- [foo]: https://example.com
'[foo]'
[foo]
"##;
    let expected = r##"<ul>
<li>
<a href="https://example.com" title="[foo]">foo</a>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0149_l2026() {
    let original = r##"[
a]: https://example.com

[b
]: https://example.com

[a] [b]
"##;
    let expected = r##"<p><a href="https://example.com">a</a> <a href="https://example.com">b</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0150_l2040() {
    let original = r##"> > ```
> > code
>
> > text
"##;
    let expected = r##"<blockquote>
<blockquote>
<pre><code>code
</code></pre>
</blockquote>
<blockquote>
<p>text</p>
</blockquote>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0151_l2060() {
    let original = r##"- *foo
  - - 
  baz*
"##;
    let expected = r##"<ul>
<li>*foo
<ul>
<li>
<ul>
<li></li>
</ul>
</li>
</ul>
baz*</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0152_l2078() {
    let original = r##"- `foo
  - - 
  baz`
"##;
    let expected = r##"<ul>
<li>`foo
<ul>
<li>
<ul>
<li></li>
</ul>
</li>
</ul>
baz`</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0153_l2096() {
    let original = r##"- [foo
  - - 
  baz](https://example.com)
"##;
    let expected = r##"<ul>
<li>[foo
<ul>
<li>
<ul>
<li></li>
</ul>
</li>
</ul>
baz](https://example.com)</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0154_l2116() {
    let original = r##"[mylink]

[mylink]: https://example.com
'
part of the title'
"##;
    let expected = r##"<p><a href="https://example.com" title="
part of the title">mylink</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0155_l2129() {
    let original = r##"1.
      pulldown-cmark used to think this was code, but commonmark.js and commonmark-hs didn't.
      The dot in the list marker is at column two, so the child paragraph actually
      starts in column *three*.
"##;
    let expected = r##"<ol>
<li>pulldown-cmark used to think this was code, but commonmark.js and commonmark-hs didn't.
The dot in the list marker is at column two, so the child paragraph actually
starts in column <em>three</em>.</li>
</ol>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0156_l2142() {
    let original = r##"1.
  This is not in the list at all. It's a paragraph after it.
"##;
    let expected = r##"<ol>
<li></li>
</ol>
<p>This is not in the list at all. It's a paragraph after it.</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0157_l2154() {
    let original = r##"`\!\&quot;\#\$\%\&
\!\&quot;\#\$\%\&
\!\&quot;\#\$\%\&`
"##;
    let expected = r##"<p><code>\!\&amp;quot;\#\$\%\&amp; \!\&amp;quot;\#\$\%\&amp; \!\&amp;quot;\#\$\%\&amp;</code></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0158_l2164() {
    let original = r##"|
-|- *
"##;
    let expected = r##"<p>|
-|- *</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0159_l2174() {
    let original = r##" A paragraph is a paragraph and spaces must be removed. 

   Another paragraph whose spaces must be removed.  
"##;
    let expected = r##"<p>A paragraph is a paragraph and spaces must be removed.</p>
<p>Another paragraph whose spaces must be removed.</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0160_l2185() {
    let original = r##"![^1]

[^1]: foo
"##;
    let expected = r##"<p>!<sup class="footnote-reference"><a href="#1">1</a></sup></p>
<div class="footnote-definition" id="1"><sup class="footnote-definition-label">1</sup>
<p>foo</p>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_FOOTNOTES");
}

#[test]
fn regression_test_0161_l2196() {
    let original = r##"First ![^1][] Second

[^1]: foo
"##;
    let expected = r##"<p>First !<sup class="footnote-reference"><a href="#1">1</a></sup>[] Second</p>
<div class="footnote-definition" id="1"><sup class="footnote-definition-label">1</sup>
<p>foo</p>
</div>
"##;

    test_markdown_html(original, expected, "ENABLE_FOOTNOTES");
}

#[test]
fn regression_test_0162_l2212() {
    let original = r##"&#00000000; &#x0000000;
"##;
    let expected = r##"<p>&amp;#00000000; &amp;#x0000000;</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0163_l2221() {
    let original = r##"&#5307530;
"##;
    let expected = r##"<p>�</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0164_l2229() {
    let original = r##"- _t
  # test
  t_
"##;
    let expected = r##"<ul>
<li>_t
<h1>test</h1>
t_</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0165_l2241() {
    let original = r##"* *_
  #
  N*
"##;
    let expected = r##"<ul>
<li>*_
<h1></h1>
N*</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0166_l2255() {
    let original = r##"
 <foo>
"##;
    let expected = r##" <foo>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0167_l2262() {
    let original = r##"
<foo>
"##;
    let expected = r##"<foo>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0168_l2269() {
    let original = r##"
   <foo>
"##;
    let expected = r##"   <foo>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0169_l2276() {
    let original = r##"* <foo>
	<bar>
"##;
    let expected = r##"<ul>
<li>
<foo>
  <bar>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0170_l2288() {
    let original = r##"* test

	 <foo>
	<bar>
"##;
    let expected = r##"<ul>
<li>
<p>test</p>
   <foo>
  <bar>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0171_l2303() {
    let original = r##"*
	 <div>
	 <div>
"##;
    let expected = r##"<ul>
<li>   <div>
   <div>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0172_l2315() {
    let original = r##"*
	<div>
	<div>
"##;
    let expected = r##"<ul>
<li>  <div>
  <div>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0173_l2327() {
    let original = r##"*
     <div>
  <div>
"##;
    let expected = r##"<ul>
<li>   <div>
<div>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0174_l2339() {
    let original = r##"*
     <div>
   <div>
"##;
    let expected = r##"<ul>
<li>   <div>
 <div>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0175_l2351() {
    let original = r##"*
      <div>
     <div>
"##;
    let expected = r##"<ul>
<li>
<pre><code>&lt;div&gt;
</code></pre>
   <div>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0176_l2367() {
    let original = r##"[link]: test (()

[link]
"##;
    let expected = r##"<p>[link]: test (()</p>
<p>[link]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0177_l2376() {
    let original = r##"[link]: test (())

[link]
"##;
    let expected = r##"<p>[link]: test (())</p>
<p>[link]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0178_l2385() {
    let original = r##"[link]: test (\(\))

[link]
"##;
    let expected = r##"<p><a href="test" title="()">link</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0179_l2393() {
    let original = r##"[link]: test """

[link]
"##;
    let expected = r##"<p>[link]: test """</p>
<p>[link]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0180_l2402() {
    let original = r##"[link]: test "\""

[link]
"##;
    let expected = r##"<p><a href="test" title="&quot;">link</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0181_l2410() {
    let original = r##"[link]: test '''

[link]
"##;
    let expected = r##"<p>[link]: test '''</p>
<p>[link]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0182_l2419() {
    let original = r##"[link]: test '\''

[link]
"##;
    let expected = r##"<p><a href="test" title="&#39;">link</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0183_l2429() {
    let original = r##"-     test

  test2
"##;
    let expected = r##"<ul>
<li>
<pre><code>test
</code></pre>
<p>test2</p>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0184_l2443() {
    let original = r##"    test

test2
"##;
    let expected = r##"<pre><code>test
</code></pre>
<p>test2</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0185_l2453() {
    let original = r##"-     test
  test2
"##;
    let expected = r##"<ul>
<li>
<pre><code>test
</code></pre>
test2</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0186_l2465() {
    let original = r##"-     test
- test2
"##;
    let expected = r##"<ul>
<li>
<pre><code>test
</code></pre>
</li>
<li>test2</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0187_l2478() {
    let original = r##"-     test

- test2
"##;
    let expected = r##"<ul>
<li>
<pre><code>test
</code></pre>
</li>
<li>
<p>test2</p>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0188_l2496() {
    let original = r##"<!p>

<\!p>
"##;
    let expected = r##"<!p>
<p>&lt;!p&gt;</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0189_l2507() {
    let original = r##"[linky]

[linky]: ((()))
"##;
    let expected = r##"<p><a href="((()))">linky</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0190_l2517() {
    let original = r##"><span
title
>junk
"##;
    let expected = r##"<blockquote>
<p>&lt;span
title
junk</p>
</blockquote>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0191_l2531() {
    let original = r##" ~~~
    ~~~
"##;
    let expected = r##"<pre><code>   ~~~
</code></pre>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0192_l2539() {
    let original = r##" ~~~
   ~~~
"##;
    let expected = r##"<pre><code></code></pre>
"##;

    test_markdown_html(original, expected, "ENABLE_STRIKETHROUGH");
}

#[test]
fn regression_test_0193_l2548() {
    let original = r##"[link]: destination "
          text          "

[link]
"##;
    let expected = r##"<p><a href="destination" title="
text          ">link</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0194_l2560() {
    let original = r##"* _
_**
  ___
  ^_
"##;
    let expected = r##"<ul>
<li>_
_**
<hr />
^_</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0195_l2576() {
    let original = r##"> [!Note]
> - Foo
"##;
    let expected = r##"<blockquote class="markdown-alert-note">
<ul>
<li>Foo</li>
</ul>
</blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_GFM");
}

#[test]
fn regression_test_0196_l2589() {
    let original = r##" ---
--
---
"##;
    let expected = r##"<hr />
<h2>--</h2>
"##;

    test_markdown_html(original, expected, "ENABLE_YAML_STYLE_METADATA_BLOCKS");
}

#[test]
fn regression_test_0197_l2604() {
    let original = r##"[30](https://rust.org/something%3A((((((((((((((((((((((((((((((())))))))))))))))))))))))))))))))
[40](https://rust.org/something%3A((((((((((((((((((((((((((((((((((((((((())))))))))))))))))))))))))))))))))))))))))
"##;
    let expected = r##"<p><a href="https://rust.org/something%3A((((((((((((((((((((((((((((((()))))))))))))))))))))))))))))))">30</a>
[40](https://rust.org/something%3A((((((((((((((((((((((((((((((((((((((((())))))))))))))))))))))))))))))))))))))))))</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0198_l2614() {
    let original = r##"- [x]		
\
-
"##;
    let expected = r##"<ul>
<li><input disabled="" type="checkbox" checked=""/></li>
</ul>
<h2>\</h2>
"##;

    test_markdown_html(original, expected, "ENABLE_TASKLISTS");
}

#[test]
fn regression_test_0199_l2627() {
    let original = r##"* [ ] 
---
bar
"##;
    let expected = r##"<ul>
<li><input disabled="" type="checkbox"/></li>
</ul>
<hr />
<p>bar</p>
"##;

    test_markdown_html(original, expected, "ENABLE_TASKLISTS");
}

#[test]
fn regression_test_0200_l2641() {
    let original = r##"`
`
"##;
    let expected = r##"<p><code> </code></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0201_l2650() {
    let original = r##"* def this
  : def text def text
"##;
    let expected = r##"<ul>
<li>
<dl>
<dt>def this</dt>
<dd>def text def text</dd>
</dl>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "ENABLE_DEFINITION_LIST");
}

#[test]
fn regression_test_0202_l2664() {
    let original = r##"* def this

  : def text def text
"##;
    let expected = r##"<ul>
<li>
<dl>
<dt>def this</dt>
<dd><p>def text def text</p></dd>
</dl>
</li>
</ul>
"##;

    test_markdown_html(original, expected, "ENABLE_DEFINITION_LIST");
}

#[test]
fn regression_test_0203_l2679() {
    let original = r##"**A:**

> B C
> I J :x: K
> :x: L M
> N O _P_ Q R. (S
> T U, V W
> :x:,:x:,:x:, and :x: but no :x: or
> :x:.)
"##;
    let expected = r##"<p><strong>A:</strong></p><blockquote>
<dl><dt>B C
I J :x: K</dt><dd>x: L M
N O <em>P</em> Q R. (S
T U, V W</dd>
<dd>x:,:x:,:x:, and :x: but no :x: or</dd>
<dd>x:.)</dd></dl></blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_DEFINITION_LIST");
}

#[test]
fn regression_test_0204_l2699() {
    let original = r##"[abc] check `foobar_raz`
 Some preamble `foobar_raz`, not `barfoo_raz`
 :D
 
 This should fix:
 
 &gt; Something is wrong!
"##;
    let expected = r##"<dl>
<dt>[abc] check <code>foobar_raz</code>
Some preamble <code>foobar_raz</code>, not <code>barfoo_raz</code></dt>
<dd>D</dd>
</dl>
<p>This should fix:</p>
<p>&gt; Something is wrong!</p>
"##;

    test_markdown_html(original, expected, "ENABLE_DEFINITION_LIST");
}

#[test]
fn regression_test_0205_l2717() {
    let original = r##"- Item definition [it
  ```rust
  ```
  stuff](https://example.com)
"##;
    let expected = r##"<ul>
<li>Item definition [it
<pre><code class="language-rust"></code></pre>
stuff](https://example.com)</li>
</ul>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0206_l2732() {
    let original = r##"foo
{.class}
===

> foo
> {.class}
> ===
>
> > foo
> > {.class}
> > ===

* > foo
  > {.class}
  > ===

> foo
>	{.class}
>	===
"##;
    let expected = r##"<h1 class="class">foo
</h1>
<blockquote>
<h1 class="class">foo
</h1>
<blockquote>
<h1 class="class">foo
</h1>
</blockquote>
</blockquote>
<ul>
<li>
<blockquote>
<h1 class="class">foo
</h1>
</blockquote>
</li>
</ul>
<blockquote>
<h1 class="class">foo
</h1>
</blockquote>
"##;

    test_markdown_html(original, expected, "ENABLE_HEADING_ATTRIBUTES");
}

#[test]
fn regression_test_0207_l2777() {
    let original = r##"the trailing space after the &gt; should be stripped
    > {.bar}
===
"##;
    let expected = r##"<h1 class="bar">the trailing space after the &gt; should be stripped
&gt;</h1>
"##;

    test_markdown_html(original, expected, "ENABLE_HEADING_ATTRIBUTES");
}

#[test]
fn regression_test_0208_l2786() {
    let original = r##"[[Wiki<|Link]]
"##;
    let expected = r##"<p><a href="Wiki%3C">Link</a></p>
"##;

    test_markdown_html(original, expected, "ENABLE_WIKILINKS");
}

#[test]
fn regression_test_0209_l2792() {
    let original = r##"* <c
  >
"##;
    let expected = r##"<ul>
<li>&lt;c
<blockquote></blockquote></li>
</ul>
"##;

    test_markdown_html(original, expected, "ENABLE_WIKILINKS");
}

#[test]
fn regression_test_0210_l2804() {
    let original = r##"- [x] * some text
- [ ] > some text
- [x]
  * some text
- [ ]
  > some text
"##;
    let expected = r##"<ul>
<li><input disabled="" type="checkbox" checked=""/>
* some text</li>
<li><input disabled="" type="checkbox"/>
&gt; some text</li>
<li><input disabled="" type="checkbox" checked=""/>
<ul>
<li>some text</li>
</ul></li>
<li><input disabled="" type="checkbox"/>
<blockquote>
<p>some text</p>
</blockquote></li>
</ul>
"##;

    test_markdown_html(original, expected, "ENABLE_TASKLISTS");
}

#[test]
fn regression_test_0211_l2832() {
    let original = r##"[a]: /url
    
:
"##;
    let expected = r##"<p>:</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0212_l2842() {
    let original = r##"[link]\[id]

[id]: https://en.wikipedia.org
"##;
    let expected = r##"<p>[link][id]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0213_l2850() {
    let original = r##"[id]\[]

[id]: https://en.wikipedia.org
"##;
    let expected = r##"<p><a href="https://en.wikipedia.org">id</a>[]</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0214_l2862() {
    let original = r##"[a](https://example.com"test")
[a](<https://example.com>"test")
[a](https://example.com(test))
[a](<https://example.com>(test))

[a](https://example.com "test")
[a](<https://example.com> "test")
[a](https://example.com (test))
[a](<https://example.com> (test))
"##;
    let expected = r##"<p><a href="https://example.com%22test%22">a</a>
[a](<a href="https://example.com">https://example.com</a>"test")
<a href="https://example.com(test)">a</a>
[a](<a href="https://example.com">https://example.com</a>(test))</p>
<p><a href="https://example.com" title="test">a</a>
<a href="https://example.com" title="test">a</a>
<a href="https://example.com" title="test">a</a>
<a href="https://example.com" title="test">a</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0215_l2888() {
    let original = r##"![[] ]()]]
"##;
    let expected = r##"<p><img src="" alt="[] " />]]</p>
"##;

    test_markdown_html(original, expected, "ENABLE_WIKILINKS");
}

#[test]
fn regression_test_0216_l2894() {
    let original = r##"a ~[x](https://x)~

b ~~[x](https://x)~~

c ~x ~~[x](https://x)~~ x~

d ~~x ~[x](https://x)~ x~~
"##;
    let expected = r##"<p>a <sub><a href="https://x">x</a></sub></p>
<p>b ~~<a href="https://x">x</a>~~</p>
<p>c ~x ~~<a href="https://x">x</a>~~ x~</p>
<p>d ~~x <sub><a href="https://x">x</a></sub> x~~</p>
"##;

    test_markdown_html(original, expected, "ENABLE_SUPERSCRIPT | ENABLE_SUBSCRIPT");
}

#[test]
fn regression_test_0217_l2912() {
    let original = r##" 
   
hello world
"##;
    let expected = r##"<p>�
���
hello�world</p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0218_l2924() {
    let original = r##"`first second`
`start `
` end`
` `
"##;
    let expected = r##"<p><code>first�second</code>
<code>start�</code>
<code>�end</code>
<code>�</code></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0219_l2938() {
    let original = r##"$$first second$$
$$start $$
$$ end$$
$$ $$
"##;
    let expected = r##"<p><span class="math math-display">first�second</span>
<span class="math math-display">start�</span>
<span class="math math-display">�end</span>
<span class="math math-display">�</span></p>
"##;

    test_markdown_html(original, expected, "ENABLE_MATH");
}

#[test]
fn regression_test_0220_l2952() {
    let original = r##"[x](x "first second")
[x](x "start ")
[x](x " end")
[x](x " ")
"##;
    let expected = r##"<p><a href="x" title="first�second">x</a>
<a href="x" title="start�">x</a>
<a href="x" title="�end">x</a>
<a href="x" title="�">x</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0221_l2969() {
    let original = r##"[x](<first second>)
[x](<start >)
[x](< end>)
[x](< >)
"##;
    let expected = r##"<p><a href="first%EF%BF%BDsecond">x</a>
<a href="start%EF%BF%BD">x</a>
<a href="%EF%BF%BDend">x</a>
<a href="%EF%BF%BD">x</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0222_l2983() {
    let original = r##"[first second]: https://example.com/a
[start ]: https://example.com/b
[ end]: https://example.com/c
[ ]: https://example.com/d

[first�second][]
[start�][]
[�end][]
[�][]
"##;
    let expected = r##"<p><a href="https://example.com/a">first�second</a>
<a href="https://example.com/b">start�</a>
<a href="https://example.com/c">�end</a>
<a href="https://example.com/d">�</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0223_l3002() {
    let original = r##"[first�second]: https://example.com/a
[start�]: https://example.com/b
[�end]: https://example.com/c
[�]: https://example.com/d

[first second][]
[start ][]
[ end][]
[ ][]
"##;
    let expected = r##"<p><a href="https://example.com/a">first�second</a>
<a href="https://example.com/b">start�</a>
<a href="https://example.com/c">�end</a>
<a href="https://example.com/d">�</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0224_l3019() {
    let original = r##"[first�second]: https://example.com/a
[start�]: https://example.com/b
[�end]: https://example.com/c
[�]: https://example.com/d

[a][first second]
[b][start ]
[c][ end]
[d][ ]
"##;
    let expected = r##"<p><a href="https://example.com/a">a</a>
<a href="https://example.com/b">b</a>
<a href="https://example.com/c">c</a>
<a href="https://example.com/d">d</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0225_l3036() {
    let original = r##"First <span title=" ">Second</span>
"##;
    let expected = r##"<p>First <span title="�">Second</span></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0226_l3042() {
    let original = r##"<div title=" ">Second</div>
"##;
    let expected = r##"<div title="�">Second</div>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0227_l3048() {
    let original = r##"```
 
```
"##;
    let expected = r##"<pre><code>�
</code></pre>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0228_l3057() {
    let original = r##"# H1 {.f  #b }
# H1 {f =b }
# H1 {f }
"##;
    let expected = r##"<h1 id="b�" class="f�">H1</h1>
<h1 f�="b�">H1</h1>
<h1 f�="">H1</h1>
"##;

    test_markdown_html(original, expected, "ENABLE_HEADING_ATTRIBUTES");
}

#[test]
fn regression_test_0229_l3067() {
    let original = r##"[a]: https://example.com/a " "

[a][]

[b](https://example.com/b " ")
"##;
    let expected = r##"<p><a href="https://example.com/a" title="�">a</a></p>
<p><a href="https://example.com/b" title="�">b</a></p>
"##;

    test_markdown_html(original, expected, "");
}

#[test]
fn regression_test_0230_l3078() {
    let original = r##"[[Z ]]
[[Z |Z ]]
"##;
    let expected = r##"<p><a href="Z%EF%BF%BD">Z�</a>
<a href="Z%EF%BF%BD">Z�</a></p>
"##;

    test_markdown_html(original, expected, "ENABLE_WIKILINKS");
}

#[test]
fn regression_test_231() {
    let original = r##"- [ ] a
  -
"##;
    let expected = r##"<ul>
<li>
<h2>[ ] a</h2>
</li>
</ul>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, false, false);
}

#[test]
fn regression_test_232() {
    let original = r##"- [ ] x

  y
  -
"##;
    let expected = r##"<ul>
<li>
<p><input disabled="" type="checkbox"/>
x</p>
<h2>y</h2>
</li>
</ul>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, false, false);
}

#[test]
fn regression_test_233() {
    let original = r##"- [x] a {#id}
  -
"##;
    let expected = r##"<ul>
<li>
<h2 id="id">[x] a</h2>
</li>
</ul>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, false, false);
}

#[test]
fn regression_test_234() {
    let original = r##"- [ ] \*a\*
  -
"##;
    let expected = r##"<ul>
<li>
<h2>[ ] *a*</h2>
</li>
</ul>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, false, false);
}

#[test]
fn regression_test_235() {
    let original = r##"- [x] a
  -

[x]: https://example.com
"##;
    let expected = r##"<ul>
<li>
<h2><a href="https://example.com">x</a> a</h2>
</li>
</ul>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, false, false);
}

#[test]
fn regression_test_236() {
    let original = r##"- [x] | one | two | three
  |-----|-----|-------
  | one | two | three
"##;
    let expected = r##"<ul>
<li><input disabled="" type="checkbox" checked=""/>
| one | two | three
|-----|-----|-------
| one | two | three</li></ul>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, false, false);
}

#[test]
fn regression_test_237() {
    let original = r##"- [x] a
  : b
- c
  : d
"##;
    let expected = r##"<ul>
<li>
<dl>
<dt>[x] a</dt>
<dd>b</dd>
</dl>
</li>
<li>
<dl>
<dt>c</dt>
<dd>d</dd>
</dl>
</li>
</ul>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, true, false, false, false);
}
