// This file is auto-generated by the build script
// Please, do not modify it manually

use super::{default_test_opts, test_markdown_html};
use pulldown_cmark::Options;

#[test]
fn super_sub_test_1() {
    let original = r##"^This is super^ ~This is sub~
"##;
    let expected = r##"<p><sup>This is super</sup> <sub>This is sub</sub></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_2() {
    let original = r##"~This is stricken out~
"##;
    let expected = r##"<p><sub>This is stricken out</sub></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_3() {
    let original = r##"~This is \~stricken~
"##;
    let expected = r##"<p><sub>This is ~stricken</sub></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_4() {
    let original = r##"~This~is~nothing~
"##;
    let expected = r##"<p><sub>This</sub>is<sub>nothing</sub></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_5() {
    let original = r##"~This ~~is not stricken.~
"##;
    let expected = r##"<p><sub>This ~~is not stricken.</sub></p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_6() {
    let original = r##"~~This ~is~~ stricken.~
"##;
    let expected = r##"<p><del>This ~is</del> stricken.~</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_7() {
    let original = r##"~This ~~is stricken~ but this is not~~
"##;
    let expected = r##"<p><sub>This ~~is stricken</sub> but this is not~~</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_8() {
    let original = r##"H~2~O

y=x^2^a+xb+c
"##;
    let expected = r##"<p>H<sub>2</sub>O</p>
<p>y=x<sup>2</sup>a+xb+c</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_9() {
    let original = r##"~foo~~

^bar^^
"##;
    let expected = r##"<p>~foo~~</p>
<p>^bar^^</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_10() {
    let original = r##"~foo^~^bar~

*foo_*_bar*
"##;
    let expected = r##"<p><sub>foo^</sub>^bar~</p>
<p><em>foo_</em>_bar*</p>
"##;

    let mut opts = default_test_opts();
    opts.insert(Options::ENABLE_SUBSCRIPT);
    opts.insert(Options::ENABLE_FOOTNOTES);
    test_markdown_html(original, expected, opts);
}

#[test]
fn super_sub_test_11() {
    let original = r##"H^+^ + OH^-^
"##;
    let expected = r##"<p>H<sup>+</sup> + OH<sup>-</sup></p>
"##;

    test_markdown_html(original, expected, false, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_12() {
    let original = r##"Ca^2+^ + CO~3~^2-^
"##;
    let expected = r##"<p>Ca<sup>2+</sup> + CO<sub>3</sub><sup>2-</sup></p>
"##;

    test_markdown_html(original, expected, false, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_13() {
    let original = r##"NH~4~^+^
"##;
    let expected = r##"<p>NH<sub>4</sub><sup>+</sup></p>
"##;

    test_markdown_html(original, expected, false, false, false, true, false, false, false);
}

#[test]
fn super_sub_test_14() {
    let original = r##"^+^ not superscript
"##;
    let expected = r##"<p>^+^ not superscript</p>
"##;

    test_markdown_html(original, expected, false, false, false, true, false, false, false);
}
