// This file is auto-generated by the build script
// Please, do not modify it manually

use super::test_markdown_html;

#[test]
fn table_captions_test_1() {
    let original = r##"Test|Table
----|-----
Test|row
: Test Caption

Test ending
"##;
    let expected = r##"<table><thead><tr><th>Test</th><th>Table</th></tr></thead><tbody>
<tr><td>Test</td><td>row</td></tr>
<caption>Test Caption</caption>
</tbody></table>
<p>Test ending</p>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn table_captions_test_2() {
    let original = r##"> Test  | Table
> ------|------
> Row 1 | Every
> Row 2 | Day
>: Test Caption
>
> Paragraph
"##;
    let expected = r##"<blockquote>
<table><thead><tr><th>Test</th><th>Table</th></tr></thead><tbody>
<tr><td>Row 1</td><td>Every</td></tr>
<tr><td>Row 2</td><td>Day</td></tr>
<caption>Test Caption</caption>
</tbody></table>
<p>Paragraph</p>
</blockquote>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn table_captions_test_3() {
    let original = r##" 1. First entry
 2. Second entry

    Col 1|Col 2
    -|-
    Row 1|Part 2
    Row 2|Part 2
    : Test Caption
"##;
    let expected = r##"<ol>
<li>
<p>First entry</p>
</li>
<li>
<p>Second entry</p>
<table><thead><tr><th>Col 1</th><th>Col 2</th></tr></thead><tbody>
<tr><td>Row 1</td><td>Part 2</td></tr>
<tr><td>Row 2</td><td>Part 2</td></tr>
<caption>Test Caption</caption>
</tbody></table>
</li>
</ol>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn table_captions_test_4() {
    let original = r##"|Col 1|Col 2|
|-----|-----|
|✓    |✓    |
|✓    |✓    |
: Done ✓
"##;
    let expected = r##"<table><thead><tr><th>Col 1</th><th>Col 2</th></tr></thead><tbody>
<tr><td>✓</td><td>✓</td></tr>
<tr><td>✓</td><td>✓</td></tr>
<caption>Done ✓</caption>
</tbody></table>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn table_captions_test_5() {
    let original = r##"|ぁ|ぃ|
|-|-|
|ぃ|ぃ|
: ぁ
"##;
    let expected = r##"<table><thead><tr><th>ぁ</th><th>ぃ</th></tr></thead><tbody>
<tr><td>ぃ</td><td>ぃ</td></tr>
<caption>ぁ</caption>
</tbody></table>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}

#[test]
fn table_captions_test_6() {
    let original = r##"|Колонка 1|Колонка 2|
|---------|---------|
|Ячейка 1 |Ячейка 2 |
: Подпись
"##;
    let expected = r##"<table><thead><tr><th>Колонка 1</th><th>Колонка 2</th></tr></thead><tbody>
<tr><td>Ячейка 1</td><td>Ячейка 2</td></tr>
<caption>Подпись</caption>
</tbody></table>
"##;

    test_markdown_html(original, expected, false, false, false, false, false, false, false, true);
}
