#!/usr/bin/env bash
set -euo pipefail

# find errors / panics
panic=0
error=0
join=0
grep "Panic caught. Pattern: " output && panic=1
grep "Couldn't convert pattern to UTF-8. Err: " output && error=1
grep "Joined thread: " output && join=1

if [ $panic -eq 1 -o $error -eq 1 -o $join -eq 1 ]; then
  echo "Panics / Errors found and printed above. Press return to continue..."
  read
fi

cargo rustc --release -- -C target-cpu=native
grep 'pattern: "' < output | sed 's/pattern: "\(.*\)"/\1/' | RUST_BACKTRACE=1 ./target/release/fuzzer --retest | tee output-retested
