#!/usr/bin/env bash
set -euo pipefail
cargo rustc --release -- -C target-cpu=native
grep 'pattern: "' < output | sed 's/pattern: "\(.*\)"/\1/' | RUST_BACKTRACE=1 ./target/release/find_exponential --retest | tee output-retested
